### ISSUE TITLE
examples/todo cannot npm install on master

### ISSUE THREAD

**Issue by rosskevin** [facebook/relay#1156]
1. Clone `master`
2. `cd examples/todo`
3. `nvm use 6.2.0`
4. `npm install`

Env:

```bash
kross:todo kross$ node -v
v6.2.0
kross:todo kross$ npm -v
3.8.9
```

Results;

```bash
kross:todo kross$ node -v
v6.2.0
kross:todo kross$ npm install

> babel-relay-plugin@0.8.1 prepublish /Users/kross/projects/relay/scripts/babel-relay-plugin
> npm run build


> babel-relay-plugin@0.8.1 build /Users/kross/projects/relay/scripts/babel-relay-plugin
> node scripts/build-lib

module.js:442
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kross/projects/relay/scripts/babel-relay-plugin/scripts/build-lib:6:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/kross/.nvm/versions/node/v6.2.0/bin/node" "/Users/kross/.nvm/versions/node/v6.2.0/bin/npm" "run" "build"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! babel-relay-plugin@0.8.1 build: `node scripts/build-lib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the babel-relay-plugin@0.8.1 build script 'node scripts/build-lib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the babel-relay-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build-lib
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs babel-relay-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls babel-relay-plugin
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kross/projects/relay/scripts/babel-relay-plugin/npm-debug.log
npm ERR! addLocal Could not install /Users/kross/projects/relay/scripts/babel-relay-plugin

> react-relay@0.8.1 prepublish /Users/kross/projects/relay
> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json && npm run build

module.js:442
    throw err;
    ^

Error: Cannot find module '/Users/kross/projects/relay/node_modules/fbjs-scripts/node/check-dev-engines.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! addLocal Could not install /Users/kross/projects/relay
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/kross/.nvm/versions/node/v6.2.0/bin/node" "/Users/kross/.nvm/versions/node/v6.2.0/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! babel-relay-plugin@0.8.1 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the babel-relay-plugin@0.8.1 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the babel-relay-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs babel-relay-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls babel-relay-plugin
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kross/projects/relay/examples/todo/npm-debug.log
```

**Comment by rosskevin** [comment]
requires `npm install` at the root of the project.
