### ISSUE TITLE
Error npm install on example/star-wars

### ISSUE THREAD

**Issue by reggi** [facebook/relay#1168]
It seems that `npm install` does the following.

* sees `"react-relay": "file:../../",` listed as a dep
* tries to install it
* then when it does sees it has a `prepublish` script and runs it (`"prepublish": "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json && npm run build"`)
* don't ask me why `prepublish` runs on `install`...
* then complains it doesn't have access to deps

WAIT

I'm not sure why this is happening at all because

`cd ../.. && npm install --ignore-scripts` should work...

```
Thomass-MBP-2:star-wars thomas$ npm install

> babel-relay-plugin@0.8.1 prepublish /Users/thomas/Desktop/relay/scripts/babel-relay-plugin
> npm run build


> babel-relay-plugin@0.8.1 build /Users/thomas/Desktop/relay/scripts/babel-relay-plugin
> node scripts/build-lib

module.js:341
    throw err;
    ^

Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/thomas/Desktop/relay/scripts/babel-relay-plugin/scripts/build-lib:3:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/thomas/.nvm/versions/node/v5.10.0/bin/node" "/Users/thomas/.nvm/versions/node/v5.10.0/bin/npm" "run" "build"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! babel-relay-plugin@0.8.1 build: `node scripts/build-lib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the babel-relay-plugin@0.8.1 build script 'node scripts/build-lib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the babel-relay-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build-lib
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs babel-relay-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls babel-relay-plugin
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thomas/Desktop/relay/scripts/babel-relay-plugin/npm-debug.log
npm ERR! addLocal Could not install /Users/thomas/Desktop/relay/scripts/babel-relay-plugin

> react-relay@0.8.1 prepublish /Users/thomas/Desktop/relay
> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json && npm run build

module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/thomas/Desktop/relay/node_modules/fbjs-scripts/node/check-dev-engines.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! addLocal Could not install /Users/thomas/Desktop/relay
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/thomas/.nvm/versions/node/v5.10.0/bin/node" "/Users/thomas/.nvm/versions/node/v5.10.0/bin/npm" "install"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! babel-relay-plugin@0.8.1 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the babel-relay-plugin@0.8.1 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the babel-relay-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs babel-relay-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls babel-relay-plugin
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thomas/Desktop/relay/examples/star-wars/npm-debug.log
```

**Comment by steveluscher** [comment]
I cleaned up the examples for the release of [0.9.0](https://github.com/facebook/relay/releases/tag/v0.9.0). Give them a try!

**Comment by steveluscher** [comment]
We're in the middle of a little bit of a revert/unrevert situation, so if anyone wants to try the examples in the next 24 hours or so be sure to check out the v0.9.0 tag:

```
git clone git@github.com:facebook/relay.git
cd relay
git checkout tags/v0.9.0
```
