### ISSUE TITLE
babel-relay-plugin fails to parse schema

### ISSUE THREAD

**Issue by WestleyArgentum** [facebook/relay#1469]
We're generating what is supposedly a relay compatible schema using postgraphql (https://github.com/calebmer/postgraphql)

When we try to parse and use the attached schema we get this error:
```
Error: RangeError: Maximum call stack size exceeded
    at _classCallCheck (/Users/westley/code/iso-relay-test/node_modules/babel-relay-plugin/lib/RelayQLAST.js:24:66)
    at new RelayQLType (/Users/westley/code/iso-relay-test/node_modules/babel-relay-plugin/lib/RelayQLAST.js:517:5)
    at RelayQLFragment.getType (/Users/westley/code/iso-relay-test/node_modules/babel-relay-plugin/lib/RelayQLAST.js:206:16)
    at shouldGenerateIdFragment (/Users/westley/code/iso-relay-test/node_modules/babel-relay-plugin/lib/RelayQLPrinter.js:583:17)
    at RelayQLPrinter.printFragment (/Users/westley/code/iso-relay-test/node_modules/babel-relay-plugin/lib/RelayQLPrinter.js:182:20)
    at /Users/westley/code/iso-relay-test/node_modules/babel-relay-plugin/lib/RelayQLPrinter.js:329:42
    at Array.forEach (native)
    at RelayQLPrinter.printSelections (/Users/westley/code/iso-relay-test/node_modules/babel-relay-plugin/lib/RelayQLPrinter.js:328:26)
    at RelayQLPrinter.printFragment (/Users/westley/code/iso-relay-test/node_modules/babel-relay-plugin/lib/RelayQLPrinter.js:188:31)
    at /Users/westley/code/iso-relay-test/node_modules/babel-relay-plugin/lib/RelayQLPrinter.js:329:42
```

We can successfully parse and use other hand-written schemas, so possibly this is a bug in postgraphql, but we're having trouble figuring out what babel-relay-plugin doesn't like about this schema in the first place.

Any advice would be greatly appreciated!

[schema.txt](https://github.com/facebook/relay/files/634627/schema.txt)

PS: the attached file is a .txt, but really it's .json -- github wouldn't let me upload it with that extension

**Comment by WestleyArgentum** [comment]
For anyone who comes across this, solution here: https://github.com/calebmer/postgraphql/issues/266

Sounds like the relay plugin will eventually have more generic support for ids, which are currently causing the problem.
