### ISSUE TITLE
Relay Transform Error when using conditional fields

### ISSUE THREAD

**Issue by felixfbecker** [facebook/relay#1500]
```tsx
const WorkbenchContainer = Relay.createContainer(WorkbenchComponent, {
	initialVariables: {
		repo: "",
		query: "",
		isSymbolUrl: false
	},
	fragments: {
		root: () => Relay.QL`
			fragment on Root {
				repository(uri: $repo) {
					symbol(query: $query) @include(if: $isSymbolUrl) {
						path
						line
					}
				}
			}
		`,
	},
});
```

Schema:

```graphql
type Repository implements Node {
	symbol(query: String!): Symbol!
}

type Symbol {
	path: String!
	line: Int!
}
```

Using this relay container with babel-relay-plugin and webpack emits `-- Relay Transform Error -- workbench.tsx --` and this stack trace at runtime:
```
Module build failed: TypeError: Cannot read property 'start' of undefined
    at Object.TaggedTemplateExpression (node_modules/babel-relay-plugin/lib/getBabelRelayPlugin.js:132:48)
    at visitorWorker (node_modules/typescript/lib/typescript.js:53912:23)
    at visitor (node_modules/typescript/lib/typescript.js:53831:24)
    at visitNode (node_modules/typescript/lib/typescript.js:42263:23)
    at Object.visitEachChild (node_modules/typescript/lib/typescript.js:42407:359)
    at visitor (node_modules/typescript/lib/typescript.js:53834:27)
    at visitNode (node_modules/typescript/lib/typescript.js:42263:23)
    at Object.visitEachChild (node_modules/typescript/lib/typescript.js:42526:108)
    at visitor (node_modules/typescript/lib/typescript.js:53834:27)
    at visitNodes (node_modules/typescript/lib/typescript.js:42311:48)
```

if I remove the `@include(if: $isSymbolUrl)` everything works fine.

**Comment by felixfbecker** [comment]
Error was on our side.
