### ISSUE TITLE
[Modern] GraphQLError doesn't actually print error message

### ISSUE THREAD

**Issue by skosch** [facebook/relay#1663]
Syntax errors in my ``graphql`...` `` blocks trip up `relay-compiler` on my machine, but `GraphQLError` is broken. All I get to see is:

```
GraphQLError
    at syntaxError (/home/sebastian/.nvm/versions/node/v7.4.0/lib/node_modules/relay-compiler/node_modules/graphql/error/syntaxError.js:28:15)
    at expect (/home/sebastian/.nvm/versions/node/v7.4.0/lib/node_modules/relay-compiler/node_modules/graphql/language/parser.js:966:32)
    at parseVariable (/home/sebastian/.nvm/versions/node/v7.4.0/lib/node_modules/relay-compiler/node_modules/graphql/language/parser.js:235:3)
    at parseVariableDefinition (/home/sebastian/.nvm/versions/node/v7.4.0/lib/node_modules/relay-compiler/node_modules/graphql/language/parser.js:223:15)
    at many (/home/sebastian/.nvm/versions/node/v7.4.0/lib/node_modules/relay-compiler/node_modules/graphql/language/parser.js:1015:16)
    at parseVariableDefinitions (/home/sebastian/.nvm/versions/node/v7.4.0/lib/node_modules/relay-compiler/node_modules/graphql/language/parser.js:213:50)
    at parseOperationDefinition (/home/sebastian/.nvm/versions/node/v7.4.0/lib/node_modules/relay-compiler/node_modules/graphql/language/parser.js:184:26)
    at parseDefinition (/home/sebastian/.nvm/versions/node/v7.4.0/lib/node_modules/relay-compiler/node_modules/graphql/language/parser.js:133:16)
    at parseDocument (/home/sebastian/.nvm/versions/node/v7.4.0/lib/node_modules/relay-compiler/node_modules/graphql/language/parser.js:106:22)
    at Object.parse (/home/sebastian/.nvm/versions/node/v7.4.0/lib/node_modules/relay-compiler/node_modules/graphql/language/parser.js:43:10)
```

**Comment by mjmahone** [comment]
Not sure how issue opening between dependencies works, but this should maybe be an issue with [graphql-js](https://github.com/graphql/graphql-js). Unless the compiler can change its parsing to handle GraphQLError better. The ideal would be to tell you what fragment + source document the error occurred (which should be possible using the `source` argument on the AST, though I'm not sure how).

**Comment by vith** [comment]
Same problem here. In the meantime I have been reading the error details with a debugger by setting a breakpoint inside `function syntaxError` in `./node_modules/graphql/error/syntaxError.js`.

Although the error doesn't seem to collect the filename, the graphql source is sufficient to identify the location.

**Comment by kassens** [comment]
When I introduce a syntax error in the example and run `yarn run build`, I get the following output which I think is as good as we can do at the moment. Please reopen an issue with a case when this still happens now!
```
% yarn run build
Using globally installed version of Yarn
yarn run v1.0.0
$ relay-compiler --src ./js/ --schema ./data/schema.graphql
HINT: pass --watch to keep watching for changes.
ERROR:
Parse error: GraphQLError: Syntax Error /Users/jkassens/Code/relay-examples/todo/js/components/TodoList.js (71:18) Expected Name, found (

70:           node {
71:             adsf((
                     ^
72:             id,
 in "components/TodoList.js"
error Command failed with exit code 100.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
