### ISSUE TITLE
babel-plugin-relay: how to use graphQl introspectionQuery?

### ISSUE THREAD

**Issue by raffihsieh** [facebook/relay#1753]
With the old "babel-relay-plugin", we could configure babel and manually  pass the plugin our schema.json ([example](https://facebook.github.io/relay/docs/guides-babel-plugin.html#advanced-usage)). On top of that, we could then use GraphQL's introspection query to ask the server to dynamically generate a schema.json that we could then pass in to the plugin.

How can we do this with the new "babel-plugin-relay" ?
From what I can see we can't do the same thing we did with the previous plugin. Is this still possible ?

**Comment by leebyron** [comment]
Yes, the same is possible, see the docs for [babel-plugin-relay](https://facebook.github.io/relay/docs/babel-plugin-relay.html) which describe the options you can provide. Passing the option `"schema": "schema.json"` will have the same effect.

You can also write a `.babelrc.js` file which is executed code if you wish you generate your schema at the moment babel is invoked.

**Comment by codepreneur** [comment]
@leebyron when I try to do this:
`src/babelRelayPlugin.js`
```
const babelRelayPlugin = require('babel-plugin-relay')
const { introspectionQuery, buildClientSchema, printSchema } = require('graphql/utilities')
const request = require('sync-request')
const fs = require('fs')
const path = require('path')
const schemaPath = path.join(__dirname, 'schema');


const graphqlHubUrl = 'https://endpoint.com/graphql'

const response = request('POST', graphqlHubUrl, {
  qs: {
    query: introspectionQuery
  }
})

console.log('response ', response)

const schema = JSON.parse(response.body.toString('utf-8'))

console.log('schema ', schema)
const graphQLSchema = buildClientSchema(schema.data);
fs.writeFileSync(
  `${schemaPath}.graphql`,
  printSchema(graphQLSchema)
);

module.exports = babelRelayPlugin(schema.data, {
  abortOnError: true
})
```
and `webpack.config.js`:

```
const path = require('path')
const webpack = require('webpack')

module.exports = {
  entry: './src/main.js',
  output: {
    path: __dirname + '/public',
    filename: 'bundle.js'
  },
  devServer: {
    inline: true,
    contentBase: './src',
    port: 3333
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify('production')
      }
    })
  ],
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {
          presets: ['es2015', 'react', 'stage-2'],
          plugins: ['transform-class-properties', __dirname + '/src/babelRelayPlugin']
        }
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
    ]
  }
}
```

I get:

```
ERROR in ./src/main.js
Module build failed: TypeError: /Users/johndoe/testing/src/main.js: Cannot read property 'functionExpression' of undefined
    at createModernNode ( /Users/johndoe/testing/node_modules/babel-plugin-relay/lib/createModernNode.js:24:11)
    at createAST ( /Users/johndoe/testing/node_modules/babel-plugin-relay/lib/compileGraphQLTag.js:85:51)
    at compileGraphQLTag ( /Users/johndoe/testing/node_modules/babel-plugin-relay/lib/compileGraphQLTag.js:75:37)
    at PluginPass.TaggedTemplateExpression ( /Users/johndoe/testing/node_modules/babel-plugin-relay/lib/BabelPluginRelay.js:42:43)
    at newFn ( /Users/johndoe/testing/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call  /Users/johndoe/testing/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call  /Users/johndoe/testing/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit ( /Users/johndoe/testing/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue ( /Users/johndoe/testing/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle  /Users/johndoe/testing/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit  /Users/johndoe/testing/node_modules/babel-traverse/lib/context.js:192:19)
 @ multi main

```

**Comment by codepreneur** [comment]
solved it by changing this line:

```
plugins: ['transform-class-properties', __dirname + '/src/babelRelayPlugin']
```

to this:

```
plugins: ['relay', 'transform-class-properties', __dirname + '/src/babelRelayPlugin']
```

will see if that will cause me any problems in the future
