### ISSUE TITLE
Hi! I can't run f8app rect native

### ISSUE THREAD

**Issue by rosskv** [facebook/relay#1801]
What's wrong?

C:\Users\user\f8app>npm start

> F8v2@0.0.1 start C:\Users\user\f8app
> babel-node ./server/server.js

C:\Users\user\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:328
        throw e;
        ^

Error: Couldn't find preset "react-native" relative to directory "C:\\Users\\user\\f8app"
    at C:\Users\user\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (C:\Users\user\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergeOptions (C:\Users\user\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:239:29)
    at OptionManager.init (C:\Users\user\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (C:\Users\user\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\Users\user\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\user\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! F8v2@0.0.1 start: `babel-node ./server/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the F8v2@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2017-05-24T14_20_49_077Z-debug.log

**Comment by sibelius** [comment]
this is a better issue for f8app repo instead of relay
