### ISSUE TITLE
relay-compiler Unexpected token somewhere

### ISSUE THREAD

**Issue by igl** [facebook/relay#1807]
Just had to do a bigger merge. Now i am encountering this:

```
$ relay-compiler --extensions jsx --src src --schema src/api/schema.graphql
HINT: pass --watch to keep watching for changes.
SyntaxError: Unexpected token (77:1)
    at Parser.pp$5.raise (/Users/igl/www/gc/node_modules/relay-compiler/node_modules/babylon/lib/index.js:4373:13)
    at Parser.pp.unexpected (/Users/igl/www/gc/node_modules/relay-compiler/node_modules/babylon/lib/index.js:1716:8)
    at Parser.pp$9.jsxParseIdentifier (/Users/igl/www/gc/node_modules/relay-compiler/node_modules/babylon/lib/index.js:6807:10)
    at Parser.pp$9.jsxParseNamespacedName (/Users/igl/www/gc/node_modules/relay-compiler/node_modules/babylon/lib/index.js:6818:19)
    at Parser.pp$9.jsxParseElementName (/Users/igl/www/gc/node_modules/relay-compiler/node_modules/babylon/lib/index.js:6833:19)
    at Parser.pp$9.jsxParseOpeningElementAt (/Users/igl/www/gc/node_modules/relay-compiler/node_modules/babylon/lib/index.js:6923:20)
    at Parser.pp$9.jsxParseElementAt (/Users/igl/www/gc/node_modules/relay-compiler/node_modules/babylon/lib/index.js:6947:29)
    at Parser.pp$9.jsxParseElement (/Users/igl/www/gc/node_modules/relay-compiler/node_modules/babylon/lib/index.js:7002:15)
    at Parser.parseExprAtom (/Users/igl/www/gc/node_modules/relay-compiler/node_modules/babylon/lib/index.js:7014:21)
    at Parser.pp$3.parseExprSubscripts (/Users/igl/www/gc/node_modules/relay-compiler/node_modules/babylon/lib/index.js:3427:19)
```

This error couldn't be less helpful.
I either manually check all changed files now, or remove relay from the build chain to get a readable error from babel.

**Comment by josephsavona** [comment]
Yeah, I ran into this too. We need to wrap the call to parse JS files with a try/catch and log more information on errors.

**Comment by sibelius** [comment]
related to https://github.com/facebook/relay/issues/1751

**Comment by wincent** [comment]
Thanks for this report!

See also #1765. @Yan-J has a fix for that incoming, and I think as part of that it prints the name of the source file in which the error occurred. So I am going to close this one as a dupe.
