### ISSUE TITLE
[babel-plugin-relay] Relay Transform Error: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by andrewBalekha** [facebook/relay#1980]
I have a problem with `react-relay/compat` `createPaginationContainer`

```javascript
export default createPaginationContainer(
  Connection,
  {
    connection: graphql`
      fragment Connection_feed on Connection {
       connection(
          first: $count
          orderBy: $orderBy
          after: $cursor
        ) @connection(key: "Feed_connection") {
          edges {
            node {
              ...Connection_feed
            }
          }
          pageInfo {
            hasNextPage
            endCursor
          }
        }
      }
    `
  },
  {
    query: graphql`
      query FeedPaginationQuery(
        $count: Int!
        $cursor: String
        $orderBy: String!
      ) {
        user {
          ...Feed_user
        }
      }
    `,
    direction: 'forward',
    getConnectionFromProps (props) {
      return props.connection
    },
    getFragmentVariables (prevVars, totalCount) {
      return {
        ...prevVars,
        count: totalCount
      }
    },
    getVariables (props, { count, cursor }, fragmentVariables) {
      return {
        count,
        cursor,
        orderBy: fragmentVariables.orderBy
      }
    }
  }
)
```

**I'm getting compilation error**

```
Relay Transform Error: Cannot read property 'toString' of undefined
```

```
TypeError: Cannot read property 'toString' of undefined
    at RelayQLType.getName (/xxx/node_modules/babel-plugin-relay/lib/RelayQLAST.js:471:86)
    at RelayQLType.mayImplement (/xxx/node_modules/babel-plugin-relay/lib/RelayQLAST.js:621:17)
    at shouldGenerateIdFragment (/xxx/node_modules/babel-plugin-relay/lib/RelayQLPrinter.js:565:27)
    ...

  93 |   },
  94 |   {
> 95 |     query: graphql`
     |            ^

    at transpile (/xxx/node_modules/babel-loader/lib/index.js:64:13)
    at Object.module.exports (/xxx/node_modules/babel-loader/lib/index.js:174:20)
```

Is here someone aware of it?

**Comment by robrichard** [comment]
In your schema, is the root query field named something other than `Query`?

```graphql
{
  __schema {
    queryType {
      name
    }
  }
}
```

If so there is a known issue with Relay compat that other names are not supported (https://github.com/facebook/relay/issues/1667). I have a PR open to address this issue: https://github.com/facebook/relay/pull/1962

**Comment by andrewBalekha** [comment]
Yes, it is named other than `Query`, let me check to change the name.

**Comment by leebyron** [comment]
This has been fixed in Relay Modern, but unfortunately a limitation of Relay Classic and Relay Compat.
