### ISSUE TITLE
Getting schema option in babel-plugin-relay to work.

### ISSUE THREAD

**Issue by satishrao84** [facebook/relay#1994]
Hello,
I am just unable to get babel-plugin-relay to work on my environment. Please help. 
I included the below in my webpack.config.js file 

`	module :{
		loaders : [
			{test: /\.js$/ , exclude:/node_modules/,
			loader : 'babel-loader',
			query:{
				presets:['react','es2015','stage-0']
				,
				plugins : ['./js/babelRelayPlugin'].map(require.resolve)
				}
			}
		]
	}`

Below is my .babelrc file 

`{
  "presets": ["es2015","react"],
  "plugins" : ["relay",{"schema":"./data/schema.json"}]
}`

When I run webpack, I get 

ERROR in ./js/app.js
Module build failed: Error: Plugin 1 specified in "/Users/sanupin/rgrjs/.babelrc" provided an invalid property of "schema"
    at Plugin.init (/Users/sanupin/rgrjs/node_modules/babel-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/Users/sanupin/rgrjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
    at /Users/sanupin/rgrjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/sanupin/rgrjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/sanupin/rgrjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/sanupin/rgrjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/sanupin/rgrjs/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/sanupin/rgrjs/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/sanupin/rgrjs/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/sanupin/rgrjs/node_modules/babel-loader/lib/index.js:49:20)
    at Object.module.exports (/Users/sanupin/rgrjs/node_modules/babel-loader/lib/index.js:174:20)

If I don't supply the  "schema", then I get a **Missing schema option. Check your .babelrc file or wherever you configure your Babel plugins to ensure the "relay" plugin has a "schema" option.**

I am using the 'react-relay' plugin in my app and I have not installed the 'relay' plugin. How should I go forward now/

**Comment by elasticsearcher** [comment]
Check out the setup in the following Found Relay example:
https://github.com/4Catalyzer/found-relay/tree/master/examples/todomvc-modern

The schema config works there so you can compare it with your setup to see what you're doing differently

**Comment by elasticsearcher** [comment]
The object that contains the schema property needs to be passed to the relay plugin and not listed as a separate plugin, so you need to specify the relay plugin as an array inside the plugin array:

{ "presets": ["es2015","react"], "plugins" : [ ["relay", {"schema":"./data/schema.json"}] ] }

**Comment by satishrao84** [comment]
Thanks for your help!
