### ISSUE TITLE
[devtools] white screen

### ISSUE THREAD

**Issue by brysgo** [facebook/relay#2138]
Hey! thanks for building relay-devtools.

I get a bunch of console warnings and errors and a white screen when trying to use relay devtools.

Relay modern 1.3-1.4.1

```
Main._createAppUI: 23.4609375ms

inspector.js:8192 Main._showAppUI: 20.44921875ms

inspector.js:8192 Main._initializeTarget: 7.949951171875ms

devtoolsPanel.js:17005 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

printWarning @ devtoolsPanel.js:17005

devtoolsPanel.js:28594 Failed to retrieve initialize state from localStorage: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

    at chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:28590:37

    at chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:57517:19

    at createStore (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:24920:33)

    at setupRedux (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:28694:33)

    at Object.defineProperty.value (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:25269:38)

    at __webpack_require__ (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:20:30)

    at Object.<anonymous> (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:59127:18)

    at __webpack_require__ (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:20:30)

    at chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:66:18

    at chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:69:10

(anonymous) @ devtoolsPanel.js:28594

devtoolsPanel.js:28608 Unable to persist state to localStorage: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

    at chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:28605:11

    at dispatch (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:25042:7)

    at chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:28725:9

    at chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:28510:18

    at dispatch (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:57524:18)

    at chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:28532:9

    at Object.loadEnvironments (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:27752:7)

    at EnvironmentChooser.componentDidMount (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:25599:18)

    at chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:45926:25

    at measureLifeCyclePerf (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:45737:12)

(anonymous) @ devtoolsPanel.js:28608

devtoolsPanel.js:28608 Unable to persist state to localStorage: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

    at chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:28605:11

    at dispatch (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:25042:7)

    at chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:28725:9

    at chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:28510:18

    at dispatch (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:57524:18)

    at callAPI.then._extends.error (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:28537:11)

    at <anonymous>

(anonymous) @ devtoolsPanel.js:28608

devtoolsPanel.js:26508 Uncaught (in promise) DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

    at new Search (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:26508:36)

    at chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:45956:18

    at measureLifeCyclePerf (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:45737:12)

    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:45955:16)

    at ReactCompositeComponentWrapper._constructComponent (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:45941:21)

    at ReactCompositeComponentWrapper.mountComponent (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:45849:21)

    at Object.mountComponent (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:6810:35)

    at ReactCompositeComponentWrapper.performInitialMount (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:46032:34)

    at ReactCompositeComponentWrapper.mountComponent (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:45919:21)

    at Object.mountComponent (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/devtoolsPanel.js:6810:35)
```
Chrome version info:
```
Google Chrome | 61.0.3163.100 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 57c9d07b416b5a2ea23d28247300e4af36329bdc-refs/branch-heads/3163@{#1250}
OS | Windows
JavaScript | V8 6.1.534.41
Flash | 27.0.0.130 C:\Users\goldsbr\AppData\Local\Google\Chrome\User Data\PepperFlash\27.0.0.130\pepflashplayer.dll
User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
```

**Comment by kassens** [comment]
The relay devtools are over at https://github.com/relayjs/relay-devtools. Closing this as there's been a new release since this issue was opened.
