### ISSUE TITLE
[FYI] undefined is not a constructor (evaluating 'new n.RecordSourceInspector(a)')

### ISSUE THREAD

**Issue by jgcmarins** [facebook/relay#2141]
Hello guys,

First of all I've already found that RecordSourceInspector was removed here: https://github.com/facebook/relay/search?q=RecordSourceInspector&type=Commits

But I am getting the following error. And it only happens after installing the app from a generated apk.

Thanks in advance.

```
10-06 10:32:46.517 13740 13791 E ReactNativeJS: undefined is not a constructor (evaluating 'new n.RecordSourceInspector(a)')
10-06 10:32:46.522 13740 13791 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
10-06 10:32:46.596 13740 13792 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
10-06 10:32:46.596 13740 13792 E AndroidRuntime: Process: -, PID: 13740
10-06 10:32:46.596 13740 13792 E AndroidRuntime: com.facebook.react.common.JavascriptException: undefined is not a constructor (evaluating 'new n.RecordSourceInspector(a)'), stack:
10-06 10:32:46.596 13740 13792 E AndroidRuntime: <unknown>@880:312
10-06 10:32:46.596 13740 13792 E AndroidRuntime: n@2:565
10-06 10:32:46.596 13740 13792 E AndroidRuntime: i@2:348
10-06 10:32:46.596 13740 13792 E AndroidRuntime: t@2:210
10-06 10:32:46.596 13740 13792 E AndroidRuntime: <unknown>@873:982
10-06 10:32:46.596 13740 13792 E AndroidRuntime: n@2:565
10-06 10:32:46.596 13740 13792 E AndroidRuntime: i@2:348
10-06 10:32:46.596 13740 13792 E AndroidRuntime: t@2:210
10-06 10:32:46.596 13740 13792 E AndroidRuntime: <unknown>@628:347
10-06 10:32:46.596 13740 13792 E AndroidRuntime: n@2:565
10-06 10:32:46.596 13740 13792 E AndroidRuntime: i@2:348
10-06 10:32:46.596 13740 13792 E AndroidRuntime: t@2:210
10-06 10:32:46.596 13740 13792 E AndroidRuntime: <unknown>@626:193
10-06 10:32:46.596 13740 13792 E AndroidRuntime: n@2:565
10-06 10:32:46.596 13740 13792 E AndroidRuntime: i@2:348
10-06 10:32:46.596 13740 13792 E AndroidRuntime: t@2:210
10-06 10:32:46.596 13740 13792 E AndroidRuntime: <unknown>@286:387
10-06 10:32:46.596 13740 13792 E AndroidRuntime: n@2:565
10-06 10:32:46.596 13740 13792 E AndroidRuntime: i@2:348
10-06 10:32:46.596 13740 13792 E AndroidRuntime: t@2:210
10-06 10:32:46.596 13740 13792 E AndroidRuntime: <unknown>@12:87
10-06 10:32:46.596 13740 13792 E AndroidRuntime: n@2:565
10-06 10:32:46.596 13740 13792 E AndroidRuntime: i@2:278
10-06 10:32:46.596 13740 13792 E AndroidRuntime: t@2:210
10-06 10:32:46.596 13740 13792 E AndroidRuntime: global code@1948:9
10-06 10:32:46.596 13740 13792 E AndroidRuntime: 
10-06 10:32:46.596 13740 13792 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
10-06 10:32:46.596 13740 13792 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
10-06 10:32:46.596 13740 13792 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-06 10:32:46.596 13740 13792 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
10-06 10:32:46.596 13740 13792 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
10-06 10:32:46.596 13740 13792 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10-06 10:32:46.596 13740 13792 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
10-06 10:32:46.596 13740 13792 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-06 10:32:46.596 13740 13792 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
10-06 10:32:46.596 13740 13792 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-06 10:32:46.596 13740 13792 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
10-06 10:32:46.596 13740 13792 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
10-06 10:32:46.597  3295 11266 W ActivityManager:   Force finishing activity -/.MainActivity
```

**Comment by kassens** [comment]
There shouldn't be any referenced to RecordSourceInspector anymore, can you try grepping over your codebase to see where it's coming from?

**Comment by sibelius** [comment]
this is happening on relay 1.4.1

**Comment by jgcmarins** [comment]
I am closing this because of `relay dev tools`.
