### ISSUE TITLE
Syntax Error: Unexpected Name "FRAGMENT"

### ISSUE THREAD

**Issue by danielfeelfine** [facebook/relay#2389]
After upgrading to *relay@1.5.0* and trying to use `relay-compiler` for compile a graphql *schema*, I got the error below:

```
ERROR:
Error loading schema. Expected the schema to be a .graphql or a .json
file, describing your GraphQL server's API. Error detail:

GraphQLError: Syntax Error: Unexpected Name "FRAGMENT"
```

Anyone knows how solve it?

Thanks

**Comment by alloy** [comment]
Can you share details about how you invoke `relay-compiler`, what your schema file looks like, and maybe run the command with `--verbose` to see if it reveals where the error is triggered from?

**Comment by danielfeelfine** [comment]
When I tried to run with `--verbose`, shows this error:

```
ERROR:
Error loading schema. Expected the schema to be a .graphql or a .json
file, describing your GraphQL server's API. Error detail:

GraphQLError: Syntax Error: Unexpected Name "FRAGMENT"
    at syntaxError (/Project/node_modules/graphql/error/syntaxError.js:24:10)
    at unexpected (/Project//node_modules/graphql/language/parser.js:1322:33)
    at parseDirectiveLocation (/Project/node_modules/graphql/language/parser.js:1242:9)
    at parseDirectiveLocations (/Project/node_modules/graphql/language/parser.js:1204:20)
    at parseDirectiveDefinition (/Project/node_modules/graphql/language/parser.js:1183:19)
    at parseTypeSystemDefinition (/Project/node_modules/graphql/language/parser.js:675:16)
    at parseDefinition (/Project/node_modules/graphql/language/parser.js:143:16)
    at parseDocument (/Project/node_modules/graphql/language/parser.js:110:22)
    at parse (/Project/node_modules/graphql/language/parser.js:38:10)
    at _getSchema (/Project/node_modules/relay-compiler/bin/relay-compiler:225:28)
From: CodegenRunner.write
    at syntaxError (/Project/node_modules/graphql/error/syntaxError.js:24:10)
    at unexpected (/Project/node_modules/graphql/language/parser.js:1322:33)
    at parseDirectiveLocation (/Project/node_modules/graphql/language/parser.js:1242:9)
    at parseDirectiveLocations (/Project/node_modules/graphql/language/parser.js:1204:20)
    at parseDirectiveDefinition (/Project/node_modules/graphql/language/parser.js:1183:19)
    at parseTypeSystemDefinition (/Project/node_modules/graphql/language/parser.js:675:16)
    at parseDefinition (/Project/node_modules/graphql/language/parser.js:143:16)
    at parseDocument (/Project/node_modules/graphql/language/parser.js:110:22)
    at parse (/Project/node_modules/graphql/language/parser.js:38:10)
    at _getSchema (/Project/node_modules/relay-compiler/bin/relay-compiler:225:28)
    at _getSchema (/Project/node_modules/relay-compiler/bin/relay-compiler:227:12)
    at Object.getSchema (/Project/node_modules/relay-compiler/bin/relay-compiler:103:19)
    at CodegenRunner.<anonymous> (/Project/node_modules/relay-compiler/bin/relay-compiler:5568:53)
    at Generator.next (<anonymous>)
    at step (/Project/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Project/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/Project/node_modules/core-js/library/modules/_export.js:35:28)
    at CodegenRunner.<anonymous> (/Project/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at CodegenRunner.write (/Project/node_modules/relay-compiler/bin/relay-compiler:5639:21)
```

**Comment by kikoseijo** [comment]
I have also seen this error and solution was to empty the file completely or left just a type, for example the Node Type.

At the end of the day this file gets generated with the information coming from server, so it does not really matter what on there.

Does this helps?

**Comment by danielfeelfine** [comment]
No @kikoseijo, this don't help me.

**Comment by danielfeelfine** [comment]
@alloy I'm invoking *relay-compiler* this way:

`relay-compiler --src ./src --schema data/schema.graphql --verbose`

**Comment by kenips** [comment]
@danielfeelfine running into this issue here and seems like mismatched graphql version is to blame. Make sure whatever is writing your `.graphql` file is matching the graphql version that relay-compiler needs (0.13.1).

**Comment by alloy** [comment]
@danielfeelfine Hey sorry for the late response. @kenips’ suggestion sounds like a good one, I’ve definitely ran into issues with different graphql-js versions for writing/reading schemas in the past.

**Comment by danielfeelfine** [comment]
It's make sense @alloy. I was trying to *compile* a *schema* generated by a different version of `graphql`. I will try again and post the results to keep the issue updated.

Thanks
