### ISSUE TITLE
Babel Relay Plugin doesn't work under Node 0.10 or 0.12

### ISSUE THREAD

**Issue by KyleAMathews** [facebook/relay#239]
But does on io.js 3.2.0.

This error is thrown on older versions of node

```
sers/kylemathews/programs/Journal/node_modules/babel-relay-plugin/src/GraphQLPrinter.js:701
    cursorType,
              ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by zpao** [comment]
#217 fixed this. Doesn't look like @yungsters got around to publishing the updated package with that.

**Comment by yungsters** [comment]
Thanks for the reminder. [babel-relay-plugin@0.2.2](https://www.npmjs.com/package/babel-relay-plugin) has been published.

**Comment by KyleAMathews** [comment]
Thanks!
