### ISSUE TITLE
TypeError: _this._resolver.isLoading is not a function

### ISSUE THREAD

**Issue by astenmies** [facebook/relay#2395]
Getting the below error when using a fragment container as a npm package.

Using the same component in the project (not as an npm package) works fine however.

node: 8.9.0
react-relay: 1.5.0
relay-compiler: 1.5.0
next: 5.0.0

Why is isLoading not in my resolver? Should I set/define/inject it somewhere from inside my app?
As a dirty hack I'm currently using a custom react-relay that has isLoading: false which is definitely not a solution.

**The error:**
```jsx
TypeError: _this._resolver.isLoading is not a function
    at new Container (/Users/bob/packages/myproject/node_modules/react-relay/lib/ReactRelayFragmentContainer.js:73:38)
    at ContainerConstructor (/Users/bob/packages/myproject/node_modules/react-relay/lib/buildReactRelayContainer.js:55:12)
```

**console.log(_this._resolver) outputs this:**
```jsx
_callback:ƒ ()
_context:{environment: RelayModernEnvironment, variables: {…}}
_data:{viewer: {…}}
_fragments:{viewer: {…}}
_onChange:ƒ ()
_props:{viewer: {…}, queryRecords: {…}, headers: {…}, token: null, url: {…}}
_resolvers:{viewer: SelectorResolver}
_stale:false
```

**In react-relay, the error is triggered from here this part (node_modules/react-relay/lib/ReactRelayFragmentContainer.js:73) :**

```jsx
var relay = assertRelayContext(context.relay);
      var createFragmentSpecResolver = relay.environment.unstable_internal.createFragmentSpecResolver;

      _this._resolver = createFragmentSpecResolver(relay, containerName, fragments, props, _this._handleFragmentDataUpdate);
      _this.state = {
        data: _this._resolver.resolve(),
        relayProp: {
          isLoading: _this._resolver.isLoading(),
          environment: relay.environment
        }
      };
      return _this;
```

**Here's the component:**

```jsx
import React from 'react';
import PropTypes from 'prop-types';
import { createFragmentContainer, graphql } from 'react-relay';

const HomePage = ({ viewer }) => (
	<div className="row">
		<div className="col-md-4 offset-md-4 text-center">
			<h1>Home</h1>
		</div>
	</div>
);

HomePage.propTypes = {
	viewer: PropTypes.shape({
		isLoggedIn: PropTypes.bool
	}).isRequired
};

// export default HomePage

export default createFragmentContainer(
	HomePage,
	graphql`
		fragment Home_viewer on Viewer {
			isLoggedIn
		}
	`
);
```

Here's the .babelrc of the npm package
```json
"presets": [
        "next/babel",
        "react",
        "es2015",
        "stage-0"
      ],
      "plugins": [
        "transform-runtime",
        [
          "relay",
          {
            "schema": "./schema/schema.graphql",
            "compat": false
          }
        ]
      ]
```

**Comment by isaldin** [comment]
@astenmies did you resolve this issue? I have the same one.
