### ISSUE TITLE
BUG: relay-compiler error when graphql found in commented code

### ISSUE THREAD

**Issue by hisapy** [facebook/relay#2535]
I was just writing a HOC and I decided to add some docs of its usage in the form of comment like the following 

```javascript
// file: lib/createForm.jsx
import React from "react";
import { createFragmentContainer } from "react-relay";

/**
 * Returns a HOC that adds Form capabilities to the Card given as param
 *
 * @param {Card} Card to wrap
 * @param {graphql} fragment to get the Form state and data
 * @param {String} formId represents the id to be given to the form tag
 */
export default function createForm(Card, fragment, formId) {
  const Form = props => {
    // Card goes here
  }

  return createFragmentContainer(Form, fragment);
}
```

I have my `yarn relay --watch` turned on and when I saved the file I got the following error

```bash
ERROR:
Parse error: Error: FindGraphQLTags: `createFragmentContainer` expects a second argument of fragment definitions. in "lib/createForm.jsx"
Watching for changes to js...
```

I turned off the `yarn relay --watch`, went through this repo issues, googling, and so on without any findings. So I went to see other similar HOC I've implemented and noticed that the only difference was the other HOC didn't have any doc comments. 

To my surprise, just at the verge of insanity, when I deleted the comments the **relay-compiler** started working again. Then I tried just deleting the word **graphql** from the comments and everything was still working, so the culprit was the word **graphql** in the Javascript comments.

Please fix this. It almost killed my sanity. 

The compilers should respect the comments as they are. And if this is an expected behavior then it should be in the DOCS and the error should be really explicit about it.

**Comment by AugustinLF** [comment]
There's no other error? Because when I run your example, I get the same error, but it's related to the fact that `createFragmentContainer` here doesn't receive directly a fragment. Removing the comment doesn't change the error for me. Perhaps you could create an example repo, so I could see how the comment poses problem?

On the other hand, I'm not sure the relay-compiler can receive anything else than a direct `graphql` tag (so far, in my different apps, I never used a query/fragment/mutation that was not declared in the same file as the component using it. But I didn't find this restriction in the docs, so yes, if it needs to be enforced, it should be added there.

**Comment by hisapy** [comment]
Hi @AugustinLF 

Let me show a more complete error stack trace I found that happens only when the compiler is _started_ ...

```bash
$ yarn relay --watch 
yarn run v1.6.0
$ relay-compiler --src ./ui --schema ./schema.json --extensions js jsx graphql --watch
ERROR:
Parse error: Error: FindGraphQLTags: `createFragmentContainer` expects a second argument of fragment definitions. in "lib/form/createForm.jsx"
Watching for changes to js...
Watching for changes to graphql...
(node:92919) UnhandledPromiseRejectionWarning: Invariant Violation: Trying to watch an uncompiled parser config: graphql
    at invariant (/Users/hisa/workspace/webapp/node_modules/fbjs/lib/invariant.js:42:15)
    at /Users/hisa/workspace/webapp/node_modules/graphql-compiler/lib/CodegenRunner.js:369:40
    at Generator.next (<anonymous>)
    at step (/Users/hisa/workspace/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/hisa/workspace/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/Users/hisa/workspace/webapp/node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:36:28)
    at /Users/hisa/workspace/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at require.watchCompile (/Users/hisa/workspace/webapp/node_modules/graphql-compiler/lib/CodegenRunner.js:396:24)
    at /Users/hisa/workspace/webapp/node_modules/graphql-compiler/lib/CodegenWatcher.js:170:17
(node:92919) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:92919) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ERROR:
Parse error: Error: FindGraphQLTags: `createFragmentContainer` expects a second argument of fragment definitions. in "lib/createForm.jsx"
Watching for changes to js...
```

This error, goes away when I remove the `graphql` word from comment. I don't know the implementation details inside the compiler but I think that this error can be traced from the line that says

```bash
(node:92919) UnhandledPromiseRejectionWarning: Invariant Violation: Trying to watch an uncompiled parser config: graphql
```

Sadly, I won' be able to create a repo for you in the next days because of deadlines but it might be helpful to know that it's currently using `react@16.3.2`

On the other hand, I have no problems passing **graphql** fragments as variables from other modules. This technique is really helpful when you have a lot of similar components and you want to standarize them in order to stay DRY and _be more productive_.

For example, I have a `createSearchField()` module which implements HOC that returns an Autocomplete based on Relay. The API looks like:

```javascript
// file: lib/createSearchField.jsx

import React from "react";
import PropTypes from "prop-types";
import { createFragmentContainer } from "react-relay";
import { Autocomplete, FontIcon, ListItem } from "react-md";

const createSearchField = (
  type,
  fragment,
  suggestionBuilder,
  baseProps = {}
) => {
  const SearchField = ({ suggestions, onFocus, onChange, ...props }) => {
    // do stuff to create a SearchField using Autocomplete
  }

  return createFragmentContainer(SearchField, fragment);
}
```

and it can be used to create SearchFields based on the data requirements, i.e.:

```javascript
// file: people/PeopleSearchField.jsx

import React from "react";
import { graphql } from "react-relay";
import { ListItem } from "react-md";

import createSearchField from "lib/search/createSearchField";

const fragment = graphql`
  # The only requirement I've experienced is the naming convention of queries, 
  # fragments and mutations documented in the Relay docs
  fragment PeopleSearchField_suggestions on PersonEdge @relay(plural: true) {
    node {
      id
      firstName
      lastName
      # other fields
    }
  }
`;

const getSecondaryText = node => {
  // return some part of node data
};

/* eslint-disable react/no-danger, react/prop-types */
const suggestionBuilder = ({ node }) => {
  const secondaryText = getSecondaryText(node);

  return (
    <ListItem
      key={node.id}
      // other ListItem props here
    />
  );
};
/* eslint-enable */

export default createSearchField("people", fragment, suggestionBuilder, {
  placeholder: "Buscar personas",
  helpText: "Por nombre, apellido, o CI"
});
```

**Comment by gilmoreorless** [comment]
I just encountered this problem in a similar scenario of creating re-usable components like a HOC. `relay-compiler` is enforcing that `createFragmentContainer` _must_ have the `graphql` template literal explicitly defined directly within the function call. I'm not sure why it's doing this, because the docs don't mention that it must be done that way.

I also got hit with the problem that it only failed when a comment was added. The reason is due to some naïve filtering logic within the compiler:

1. The parser looks for calls to `createFragmentContainer` (and other similar methods) and enforces that the 2nd argument contains inline `graphql` template literals: https://github.com/facebook/relay/blob/7dc0da69197ad888bbda55a493a42d7be68d1599/packages/relay-compiler/language/javascript/FindGraphQLTags.js#L98
2. The parser step is theoretically only run on files that contain `graphql` fragments (as a performance optimisation I presume). But the actual check simply looks at the text of the file for the exact string `graphql`: https://github.com/facebook/relay/blob/4d32b84d3b3269b96ca693fffc24c6445673b09e/packages/relay-compiler/core/RelaySourceModuleParser.js#L118
3. Thus, when the file containing the abstract wrapper around `createFragmentContainer` is written without comments, it's not run through the parser at all. But as soon as it contains the text `graphql` **anywhere** in the file (even in comments), it gets sent to the parser, which complains.

I don't see why the parser is so strict on how the call to `createFragmentContainer` is constructed. It really hinders usage of legitimate code abstraction techniques.

**Comment by sibelius** [comment]
Migrate to new relay compiler in rust, if the issue still valid, open another issue
