### ISSUE TITLE
Can't run any examples

### ISSUE THREAD

**Issue by adriantoine** [facebook/relay#254]
I cloned the repo and tried:
`cd relay/`
`npm install` (this is needed to avoid issue stated here: https://github.com/facebook/relay/issues/248)
`cd examples/todo`
`npm install`
`npm start`

And I get this error on `npm start`:
```
$ npm start

> @ start /home/adrien/projects/relay/examples/todo
> babel-node ./server.js

GraphQL Server is now running on http://localhost:8080
Relay TodoMVC is now running on http://localhost:3000
Hash: 9a56cc72acac2de6f40c
Version: webpack 1.12.1
Time: 2095ms

Module build failed: /home/adrien/projects/relay/examples/todo/node_modules/babel-relay-plugin/src/GraphQLPrinter.js:701
    cursorType,
              ^
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/adrien/projects/relay/examples/todo/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/adrien/projects/relay/examples/todo/node_modules/babel-relay-plugin/src/GraphQLDocumentTransformer.js:6:22)
    at Module._compile (module.js:460:26)
```

Note that I don't have any errors on install, only on `npm start`, I have tried `npm cache clean` and I get the same error with the other examples: `relay-treasurehunt/` and `star-wars/`.

**Comment by adriantoine** [comment]
I found the issue and fixed it, see PR.
