### ISSUE TITLE
Support Yarn PnP

### ISSUE THREAD

**Issue by steida** [facebook/relay#2698]
I am playing with Yarn PnP and it seems, that relay-compiler needs to update its dependencies. Am I correct?

```
Error: Package "relay-compiler@3.0.0" (via "/Users/steida/Library/Caches/Yarn/v4/npm-relay-compiler-3.0.0-689015f2aa638296c82c5761e5b4cdb09aed7139/node_modules/relay
-compiler/bin/relay-compiler") is trying to require the package "core-js" (via "core-js/es6") without it being listed in its dependencies (graphql, @babel/generator, @b
abel/parser, @babel/polyfill, @babel/runtime, @babel/traverse, @babel/types, babel-preset-fbjs, chalk, fast-glob, fb-watchman, fbjs, immutable, nullthrows, relay-runtim
e, signedsource, yargs, relay-compiler)
 |     at makeError (/Users/steida/dev/este/.pnp.js:55:17)
 |     at Object.resolveToUnqualified (/Users/steida/dev/este/.pnp.js:16133:17)
 |     at Object.resolveRequest (/Users/steida/dev/este/.pnp.js:16204:31)
 |     at Function.Module._resolveFilename (/Users/steida/dev/este/.pnp.js:16386:30)
 |     at Function.Module._load (/Users/steida/dev/este/.pnp.js:16302:31)
 |     at Module.require (module.js:596:17)
 |     at require (packages/relay/internal/module.js:11:18)
 |     at Object.<anonymous> (/Users/steida/Library/Caches/Yarn/v4/npm-relay-compiler-3.0.0-689015f2aa638296c82c5761e5b4cdb09aed7139/node_modules/relay-compiler/bin/rel
ay-compiler:14659:18)
 |     at __webpack_require__ (/Users/steida/Library/Caches/Yarn/v4/npm-relay-compiler-3.0.0-689015f2aa638296c82c5761e5b4cdb09aed7139/node_modules/relay-compiler/bin/re
lay-compiler:30:30)
 |     at Object.<anonymous> (/Users/steida/Library/Caches/Yarn/v4/npm-relay-compiler-3.0.0-689015f2aa638296c82c5761e5b4cdb09aed7139/node_modules/relay-compiler/bin/rel
ay-compiler:9651:1)
```

**Comment by robrichard** [comment]
I think the issue is here: 

https://github.com/facebook/relay/blob/master/gulpfile.js#L119

Relay compiler is bundled by webpack into `bin/relay-compiler`. I think the intention of the `externals` regex was to exclude any third party modules from the bundle, but it does not match `@babel/polyfill`.

So that package is inlined into `relay-compiler` but it's imports from `core-js` are not. Now to yarn pnp it looks like relay-compiler is importing `core-js` directly without specifying it as a dependency.

**Comment by koistya** [comment]
Does anybody have a workaround for this issue? Adding `relay-compiler-language-typescript` to the list of dependencies doesn't help.

```
yarn relay-compiler --src ./src --schema ./schema.graphql --language typescript --watchman false

Error: relay-compiler tried to access relay-compiler-language-typescript, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: relay-compiler-language-typescript (via "relay-compiler-language-typescript")
Required by: relay-compiler@virtual:4b7d1bc29a95224e8b73409602711ceae3e3617ba669b94a6bb440fdde6eee0f04fcc2045c82446b93cc206f1d01e3f44ad36f3d127ba0a6c7f194a3d98bcce8#npm:9.0.0 (via .yarn/$$virtual/relay-compiler-virtual-324a6ac921/0/cache/relay-compiler-npm-9.0.0-ef7da72b90-2.zip/node_modules/relay-compiler/bin/)

Require stack:
- .yarn/$$virtual/relay-compiler-virtual-324a6ac921/0/cache/relay-compiler-npm-9.0.0-ef7da72b90-2.zip/node_modules/relay-compiler/bin/relay-compiler
    at Object.makeError (.pnp.js:25536:34)
    at resolveToUnqualified (.pnp.js:32896:37)
    at resolveRequest (.pnp.js:32986:27)
    at Object.resolveRequest.maybeLog [as resolveRequest] (.pnp.js:33054:26)
    at Function.module_1.Module._resolveFilename (.pnp.js:32249:34)
    at Function.module_1.Module._load (.pnp.js:32134:40)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at getLanguagePlugin (.yarn/$$virtual/relay-compiler-virtual-324a6ac921/0/cache/relay-compiler-npm-9.0.0-ef7da72b90-2.zip/node_modules/relay-compiler/bin/relay-compiler:7517:41)
    at Object.getCodegenRunner (.yarn/$$virtual/relay-compiler-virtual-324a6ac921/0/cache/relay-compiler-npm-9.0.0-ef7da72b90-2.zip/node_modules/relay-compiler/bin/relay-compiler:7670:24)
```

**Comment by josephsavona** [comment]
We're open to PRs to extend Relay to support PnP, but this isn't something we will likely prioritize ourselves until PnP is widely adopted.

**Comment by arcanis** [comment]
The problem is that the language server is loaded through a [direct require call](https://github.com/facebook/relay/blob/5ce9bd5e1e3ab3216b5a44280db40602ea31b56b/packages/relay-compiler/bin/RelayCompilerMain.js#L135), so it relies on the specific hoisting layout (if a sibling dependency simply happens to depend on the language plugin, relay-compiler won't find the root one anymore).

Since the plugin is loaded from the `cwd` [a few lines above](https://github.com/facebook/relay/blob/5ce9bd5e1e3ab3216b5a44280db40602ea31b56b/packages/relay-compiler/bin/RelayCompilerMain.js#L129), I believe an improvement would be to do the same for the server resolution, using the `paths` property:

```ts
const req = eval('require');
languagePlugin = req(req.resolve(requirePath, {
  paths: [process.cwd()],
}));
```

In the meantime, and as a workaround, you can use [`packageExtensions`](https://yarnpkg.com/configuration/yarnrc#packageExtensions) to force-declare a dependency on `relay-compiler-language-typescript` (or any other language) to `relay-compiler`.

**Comment by xyy94813** [comment]
How prevalent is PNP in 2021?
Is the feature being considered for continued promotion?

I am evaluating whether to use PnP in my Relay project.

**Comment by xyy94813** [comment]
Can I use `pnpm` as an alternative
