### ISSUE TITLE
RelayCompilerMain.js uncatchable errors

### ISSUE THREAD

**Issue by jazblueful** [facebook/relay#2815]
I'm using relay-compiler as library directly in my node javascript code and not the cli to automatically re-run relay-compiler when a change is detected. If there are no errors, continue recompiling rest of the javascript code using webpack. If error is detected, print out the error and wait for new changes.

```javascript
import { main } from 'relay-compiler/lib/RelayCompilerMain';

try {
  main({
      schema,
      src,
      // ... etc
  }).catch(e => {
      console.error(e);
  });
} catch(e => {
  console.error(e);
});
```

The piece of code above is unable to catch RelayParser errors thrown inside RelayCompilerMain.js and terminates the process with:
```
RelayParser: Encountered 1 error(s):
- Unknown field 'title' on type 'Post'. Source: document `usePost_post` file: `hooks/usePost.js`
  
  hooks/usePost.js:7:5
  6 |     title
  7 |     content
    |     ^
  8 |   }
```

**Comment by josephsavona** [comment]
Hmm, that is strange. RelayParser throws standard errors that can be caught w try/catch: we do so in our unit tests. Are you able to share a full stacktrace for the error? My guess is that this has to do w how the code is getting transformed.

**Comment by jazblueful** [comment]
That is strange ideed. I guess I'm doing something wrong ... again :)

Here is the stacktrace:
```
From: CodegenRunner.write
    at createCombinedError (/usr/src/service/node_modules/relay-compiler/lib/RelayCompilerError.js:79:10)
    at RelayParser.transform (/usr/src/service/node_modules/relay-compiler/lib/RelayParser.js:189:13)
    at /usr/src/service/node_modules/relay-compiler/lib/RelayParser.js:101:19
    at Object.run (/usr/src/service/node_modules/relay-compiler/lib/GraphQLCompilerProfiler.js:54:30)
    at transform (/usr/src/service/node_modules/relay-compiler/lib/RelayParser.js:99:19)
    at convertASTDefinitions (/usr/src/service/node_modules/relay-compiler/lib/ASTConvert.js:118:10)
    at /usr/src/service/node_modules/relay-compiler/lib/ASTConvert.js:101:12
    at Object.run (/usr/src/service/node_modules/relay-compiler/lib/GraphQLCompilerProfiler.js:54:30)
    at Object.convertASTDocumentsWithBase (/usr/src/service/node_modules/relay-compiler/lib/ASTConvert.js:42:19)
    at compileAll (/usr/src/service/node_modules/relay-compiler/lib/RelayFileWriter.js:75:32)
```

**Comment by josephsavona** [comment]
Hmm, that whole stack trace is in Relay compiler. Where do you call compileAll?

**Comment by jazblueful** [comment]
I get this stacktrace when I call main with { verbose: true }

Otherwise I don't get any stacktrace at all.

**Comment by jazblueful** [comment]
I'm calling main from js script I run from my terminal window using babel-node.

**Comment by josephsavona** [comment]
That's really strange. `compileAll()` is called from within `main()`, so I'd expect the latter to appear in the stack as well. Are you transforming the code with anything? Maybe restructuring to use a promise will work:

```
new Promise(() => {
  main()
}).catch(error => ...)
```

**Comment by sibelius** [comment]
Try to add await before main

**Comment by jazblueful** [comment]
I tried that too before opening an issue.

I have created a repo to demonstrate the issue: https://github.com/jazblueful/react-starter-kit/blob/master/tools/start.js#L137

After cloning and installing the dependancies, run "npm run start" to see the output.

Thanks for trying to help me out with this issue, I admire your persistence.

**Comment by kassens** [comment]
`main` quits with 100 if an error happened: https://github.com/facebook/relay/blob/master/packages/relay-compiler/bin/RelayCompilerMain.js#L200

I suppose `RelayCompilerMain.main` could return the `result` enum and `RelayCompilerBin` could exit with error, that way you'd have to check for the result and do what you want to do, but shouldn't `yarn start` fail with error if it fails to compile?
