### ISSUE TITLE
Error when runs relay-compiler with --langue typescript

### ISSUE THREAD

**Issue by fedbalves** [facebook/relay#2906]
When you run relay-compiler using typescript it throws a Error at 7.0.0.

**RUN**
relay-compiler --artifactDirectory ./src/__generated__ --language typescript --src ./src --schema ./schema.graphql --extensions ts tsx

**TRACE**
Error: Cannot find module 'relay-compiler/lib/transforms/RelayMaskTransform'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/fedbalves/Repositories/captalys/jovian/node_modules/relay-compiler-language-typescript/lib/TypeScriptGenerator.js:47:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by sibelius** [comment]
follow this https://github.com/relay-tools/relay-compiler-language-typescript/issues/151
