### ISSUE TITLE
Missing script: relay-compiler

### ISSUE THREAD

**Issue by alejomonp** [facebook/relay#3460]
Console log (not actual debug log):
```
npm ERR! missing script: relay-compiler

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Eugenio\AppData\Roaming\npm-cache\_logs\2021-04-18T01_05_17_199Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! al-kindi@0.1.0 relay: `npm run relay-compiler --schema schema.graphql --src ./src/ --watchman false $@`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the al-kindi@0.1.0 relay script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Eugenio\AppData\Roaming\npm-cache\_logs\2021-04-18T01_05_17_268Z-debug.log
```

Debugging logs:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'relay'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prerelay', 'relay', 'postrelay' ]
5 info lifecycle al-kindi@0.1.0~prerelay: al-kindi@0.1.0
6 info lifecycle al-kindi@0.1.0~relay: al-kindi@0.1.0
7 verbose lifecycle al-kindi@0.1.0~relay: unsafe-perm in lifecycle true
8 verbose lifecycle al-kindi@0.1.0~relay: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Eugenio\Documents\AlKindi\tempo\al-kindi\node_modules\.bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python38\Scripts\;C:\Python38\;C:\Users\Eugenio\AppData\Roaming\npm;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Windows\system32;C:\Program Files\nodejs\;C:\Program Files (x86)\QuickTime\QTSystem\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\Eugenio\AppData\Local\Programs\Microsoft VS Code\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Python38\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Users\Eugenio\AppData\Roaming\npm;C:\Windows\System32\WindowsPowerShell\v1.0;;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
9 verbose lifecycle al-kindi@0.1.0~relay: CWD: C:\Users\Eugenio\Documents\AlKindi\tempo\al-kindi
10 silly lifecycle al-kindi@0.1.0~relay: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npm run relay-compiler --schema schema.graphql --src ./src/ --watchman false $@'
10 silly lifecycle ]
11 silly lifecycle al-kindi@0.1.0~relay: Returned: code: 1  signal: null
12 info lifecycle al-kindi@0.1.0~relay: Failed to exec relay script
13 verbose stack Error: al-kindi@0.1.0 relay: `npm run relay-compiler --schema schema.graphql --src ./src/ --watchman false $@`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid al-kindi@0.1.0
15 verbose cwd C:\Users\Eugenio\Documents\AlKindi\tempo\al-kindi
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "relay"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error al-kindi@0.1.0 relay: `npm run relay-compiler --schema schema.graphql --src ./src/ --watchman false $@`
22 error Exit status 1
23 error Failed at the al-kindi@0.1.0 relay script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

/package.json went like this:
```
{
  "name": "al-kindi",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.10",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^12.8.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-relay": "^11.0.2",
    "react-scripts": "4.0.3",
    "relay-runtime": "^11.0.2",
    "web-vitals": "^1.1.1"
  },
"scripts": {
    "start": "npm run relay & react-scripts start",
    "build": "npm run relay & react-scripts build",
    "test": "react-scripts test",
    "relay": "npm run relay-compiler --schema schema.graphql --src ./src/ --watchman false $@",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "babel-plugin-relay": "^11.0.2",
    "graphql": "^15.5.0",
    "relay-compiler": "^11.0.2"
  }
}
```

Yes, the schema.graphql is on UTF-8.
Yes, I did execute:
npm install --save relay-runtime react-relay
npm install --save-dev relay-compiler graphql babel-plugin-relay
Lastly, I'm running on Visual Studio Code. OS: Windows 10 x64

Thanks in advance! ٩(◕‿◕｡)۶

**Comment by anatooly** [comment]
Can you use use relay-compiler manual? May be need PATH for node_modules bin folders.

$ relay-compiler --version
relay-compiler: command not found
$ node node_modules/relay-compiler/bin/relay-compiler --version
10.1.2
