### ISSUE TITLE
Backward pagination issue - "Expected forward pagination metadata to be available"

### ISSUE THREAD

**Issue by pawel3ala** [facebook/relay#3529]
Hey Guys, I've been trying to make it work for quite a bit of a time and I think I am stuck and need some help
Not sure if it's a bug (as error message suggests) or maybe I miss someting?
Many thanks in advance for any help/leads ...

```
  const { data, loadNext, refetch } = usePaginationFragment(
    graphql`
      fragment UserGroupList_User on User @refetchable(queryName: "UserGroupListPaginationQuery") {
        id
        groups(last: $count, before: $cursor) @connection(key: "UserGroupListList_groups") {
          edges {
            node {
              id
              name
              ...GroupRow_Group
            }
          }
        }
      }
    `,
    props
  );
```

When I try rendering the screen I get this nasty bold red error;
```
Invariant Violation: Relay: Expected forward pagination metadata to be available. If you're seeing this, this is likely a bug in Relay.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

**Comment by josephsavona** [comment]
If you're trying to paginate backward, note that you should call the `loadPrevious` function returned from `usePaginationFragment`. In order to call `loadNext()`, you have to pass `first` and `after` arguments.

**Comment by pawel3ala** [comment]
I tried `loadPrevious` as well and the outcome was that the list I got fetched was not inverted at all :/

**Comment by josephsavona** [comment]
To confirm, the way Relay's pagination works is as follows. Imagine you've loaded an initial set of items A B C. If you call `loadPrevious()`, you'd expect to see X Y Z A B C in order (ie, the "previous" N items in the list would be prepended such that they appear in consecutive order). If you call `loadNext()`, you'd expect to see A B C D E F, ie the next N items are appended in-order. Generally speaking, the after/first arguments should be used in a schema to fetch items that are conceptually subsequent-to the `after` cursor - so it sounds like you may need to adjust the API so that you can pass first/after and call loadNext().

**Comment by Albert-Gao** [comment]
@josephsavona  I see, so it means, the way relay handles pagination is not capable of doing a real pagination, like go to next page then go back to previous page? new data ALWAYS added on top of existing data?

which explains why I am experiencing such bug in https://github.com/facebook/relay/issues/4058
