### ISSUE TITLE
[relay 13] `relay test util` version 13 makes an error when importing itself.

### ISSUE THREAD

**Issue by DevYuns** [facebook/relay#3718]
## package version
- `"relay-test-utils": "^13.0.0-rc.2"`
- `"relay-runtime": "^13.0.0-rc.2"`

## Issue
when I tried to test with `relay-test-utils`, It throw an error like below.

```
  ● Test suite failed to run

    Cannot find module 'relay-runtime/store/ResolverFragments' from 'node_modules/relay-test-utils/lib/RelayResolverTestUtils.js'

    Require stack:
      node_modules/relay-test-utils/lib/RelayResolverTestUtils.js
      node_modules/relay-test-utils/lib/index.js
      node_modules/relay-test-utils/index.js
      src/components/pages/__tests__/MainFriend.test.tsx

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/relay-test-utils/lib/RelayResolverTestUtils.js:13:25)
```

And my test code just like below.

```
//

import {MockPayloadGenerator, createMockEnvironment} from 'relay-test-utils';

//

mockEnvironment.mock.queueOperationResolver((operation) => {
  return MockPayloadGenerator.generate(operation, {
    User: (_, generateId): User => ({
      id: `user-${generateId()}`,
      name: 'John Doe',
      nickname: 'jdoe1234',
    }),
    PageInfo: () => ({has_next_page: false}),
  });
});

//
```

since I don't need a `RelayResolverTestUtils` module still now, I just removed that line of code in `node_modules`. After then, The test was passed.

`node_modules/relay-test-utils/lib/index.js`

```
//

var testResolver = require('./RelayResolverTestUtils');  // Remove this line

var unwrapContainer = require('./unwrapContainer');

/**
 * The public interface to Relay Test Utils.
 */
module.exports = {
  MockEnvironment: RelayModernMockEnvironment,
  MockPayloadGenerator: RelayMockPayloadGenerator,
  createMockEnvironment: RelayModernMockEnvironment.createMockEnvironment,
  unwrapContainer: unwrapContainer,
  testResolver: testResolver // Remove this line
};

```

**Comment by alunyov** [comment]
Thanks for the report. Fix is coming.

**Comment by alunyov** [comment]
Should be fixed here: https://github.com/facebook/relay/commit/a93d92231215f680d81482675971b33afd6c1ba0

**Comment by DevYuns** [comment]
@alunyov Awesome! Thank you for rapid reply.
