### ISSUE TITLE
New version of relay compiler does not recognize language config options on Linux

### ISSUE THREAD

**Issue by TikiTDO** [facebook/relay#3783]
I am trying to upgrade to `relay-compiler` version 13 on my Linux development machine, and the compiler is complaining that it does not recognize the `language` parameter.

Here is my `relay.config.js` file: 

```js
module.exports = {
  excludes: ["**/node_modules/**", "**/__mocks__/**", "**/__generated__/**"],
  language: "typescript",
  schema: "./backend/schema.graphql",
  src: "./packages/common-react/src",
}
```

When running the compiler I get the following output:

```
└> RUST_BACKTRACE=1 yarn relay
yarn run v1.22.17
$ relay-compiler
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("The config file cannot be parsed as a multi-project config file due to:\n- Error(\"unknown field `language`, expected one of `name`, `root`, `header`, `codegenCommand`, `sources`, `excludes`, `projects`, `featureFlags`, `savedStateConfig`, `isDevVariableName`\", line: 0, column: 0).\n\nIt also cannot be a single project config file due to:\n- Error(\"invalid type: string \\\"true\\\", expected a boolean\", line: 0, column: 0).", line: 0, column: 0)', /home/runner/work/relay/relay/compiler/crates/js-config-loader/src/loader.rs:72:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   3: <js_config_loader::loader::JsLoader as js_config_loader::loader::Loader<T>>::load
   4: js_config_loader::search
   5: relay_compiler::config::Config::search
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: tokio::park::thread::CachedParkThread::block_on
   8: tokio::runtime::thread_pool::ThreadPool::block_on
   9: tokio::runtime::Runtime::block_on
  10: relay::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error Command failed with exit code 101.
```

The version seems correct:

```
└> yarn relay --version
yarn run v1.22.17
$ relay-compiler --version
Relay Compiler 13.0.2
```

I can reproduce this by running the executable directly from `node_modules/relay-compiler/linux-x64/relay`. Did I miss a step somewhere, or is it possible that the linux binary is using an incorrect code path somehow?

**Comment by alunyov** [comment]
Hmm, I don't think it is related to `language`. The `language` it is just the first part of this big error message, that is saying that the compiler cannot parse config as multi-project config. The second part of the error messages in more interesting: 

```
"invalid type: string \\\"true\\\", expected a boolean\"
``` 

But I don't see "true" string in your example. Maybe you have a different config somewhere?

**Comment by TikiTDO** [comment]
Ah, yep. Looks like that was it. There was another old `relay.config.js` that I missed. Thanks.
