### ISSUE TITLE
thread '<unnamed>' panicked at 'Expected `Node` to contain a field named `id`.', crates/relay-transforms/src/generate_id_field.rs:128:25

### ISSUE THREAD

**Issue by husseinhere** [facebook/relay#3807]
Using 13.1.1 on my project:

```
thread '<unnamed>' panicked at 'Expected `Node` to contain a field named `id`.', crates/relay-transforms/src/generate_id_field.rs:128:25
stack backtrace:
   0:        0x1048b3bc4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h98d8e939df2a84c8
   1:        0x1048d068c - core::fmt::write::ha8927896f8d44e8d
   2:        0x1048ac2a4 - std::io::Write::write_fmt::h5be52fc0ae77f963
   3:        0x1048b5370 - std::panicking::default_hook::{{closure}}::h7ab34c9d6fd8d067
   4:        0x1048b4f50 - std::panicking::default_hook::h6507a23c659c2199
   5:        0x1048b59b0 - std::panicking::rust_panic_with_hook::h032de7ae9e9d479f
   6:        0x1048b54fc - std::panicking::begin_panic_handler::{{closure}}::ha7b561c0fbbe4ae5
   7:        0x1048b4084 - std::sys_common::backtrace::__rust_end_short_backtrace::h0ff1db7619f9e51e
   8:        0x1048b5464 - _rust_begin_unwind
   9:        0x1049209bc - core::panicking::panic_fmt::h660aa0926f67c6d3
  10:        0x1046e637c - relay_transforms::generate_id_field::GenerateIDFieldTransform::new::{{closure}}::h5331926dc5e65bc2
  11:        0x1046e5070 - relay_transforms::generate_id_field::generate_id_field::ha086b1e43b1d287c
  12:        0x104358edc - relay_transforms::apply_transforms::apply_operation_transforms::hd729282af10b1a3d
  13:        0x10436f474 - relay_transforms::apply_transforms::apply_transforms::{{closure}}::{{closure}}::h1c53f4ec7189e4ce
  14:        0x10436d0c4 - rayon_core::join::join_context::{{closure}}::h123d330bfc7f7aa7
  15:        0x1043bfd2c - common::sync::try_join::h7a2767ad2d64f3b0
  16:        0x10436f3b4 - relay_transforms::apply_transforms::apply_transforms::{{closure}}::h5973432c5b692ff6
  17:        0x10436e290 - rayon_core::join::join_context::{{closure}}::ha7af39fb8fdd124b
  18:        0x104370070 - std::panicking::try::h82c39509b3a78e48
  19:        0x1043c0830 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h3d87319c9f6f0245
  20:        0x10491ad6c - rayon_core::registry::WorkerThread::wait_until_cold::ha9c7498ad521f6a4
  21:        0x104823790 - rayon_core::registry::ThreadBuilder::run::h15bfdc0cdc8721c8
  22:        0x104825818 - std::sys_common::backtrace::__rust_begin_short_backtrace::h90d514b06eaf30e9
  23:        0x104826704 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h7f2088aecfbf73b5
  24:        0x1048ba0bc - std::sys::unix::thread::Thread::new::thread_start::h8d5e19fc4f27caac
  25:        0x19ff014ec - _pthread_from_mach_thread_np
  ```
  
  Not sure exactly which graphql query is causing that...

**Comment by husseinhere** [comment]
Ah, the problem went away when I used `nodeInterfaceIdField: "nodeId"` in the configuration. I guess relay should give a bit better error of what the problem was

**Comment by jindrake** [comment]
@husseinhere hi, can you point to where `nodeInterfaceIdField` config is documented? thanks

**Comment by josephsavona** [comment]
Great catch. Any interest in sending a PR to help improve the error message here?
