### ISSUE TITLE
13.2.0 Trying to iterate through `relayResolverErrors` when it is undefined crashes app.

### ISSUE THREAD

**Issue by TLadd** [facebook/relay#3919]
I'm running into the same error as https://github.com/facebook/relay/issues/3843 upgrading my app from relay 13.1.0 to 13.2.0. The stacktrace points to this line: https://github.com/facebook/relay/blob/main/packages/relay-runtime/util/handlePotentialSnapshotErrors.js#L25. Stepping through the code, `relayResolverErrors` is undefined, which the flow types do not seem to be expecting. This is the full stack trace I get:

```
createForOfIteratorHelper.js:4 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at _createForOfIteratorHelper (createForOfIteratorHelper.js:4:1)
    at handlePotentialSnapshotErrors (handlePotentialSnapshotErrors.js:18:1)
    at FragmentResourceImpl._handlePotentialSnapshotErrorsInSnapshot (FragmentResource.js:394:1)
    at FragmentResourceImpl.readWithIdentifier (FragmentResource.js:282:1)
    at useFragmentNode (useFragmentNode.js:39:1)
    at useLazyLoadQueryNode (useLazyLoadQueryNode.js:108:1)
    at useLazyLoadQuery (useLazyLoadQuery.js:34:1)
    at App (App.tsx:51:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at mountIndeterminateComponent (react-dom.development.js:20913:1)
```

**Comment by captbaritone** [comment]
Thanks for reporting @TLadd. The stacktrace was super helpful. What version of `relay-runtime` are you using?

Is it possible that you upgraded `react-relay` without upgrading `relay-runtime`?

**Comment by TLadd** [comment]
@captbaritone Apologies for not responding sooner!

You are correct that it appears to be an issue with mismatched versions of `relay-runtime` (via `relay-compiler`). Turned out there were two versions of relay-compiler and relay-runtime in my lockfile. The project I'm working on is in a monorepo and another project within the repo is making use of [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator). A bunch of the `@graphql-codegen` packages end up depending on `@graphql-tools/relay-operation-optimizer`, whose latest version still depends on relay-compiler 12.0.0. 

Adding a resolutions field to `package.json` forcing all uses of `relay-compiler` to 13.2.0 gets rid of the error.
