### ISSUE TITLE
Flow problems and jest fails when using npm3

### ISSUE THREAD

**Issue by clentfort** [facebook/relay#396]
By default npm3 flattens the `node_modules` directory. This results in the nested path defined in [`.flowconfig`](https://github.com/facebook/relay/blob/master/src/.flowconfig#L9) not being valid. Furthermore there are problems running `jest`. All tests fail with a runtime error (see attached output of `npm t`). I assume this has something to do how jest is configured to transform the source before running the tests.

```
npm t

> react-relay@0.3.2 test /home/christian/js/relay
> f() { EXIT=0; npm run typecheck || EXIT=$?; NODE_ENV=test jest $@ || EXIT=$?; exit $EXIT; }; f


> react-relay@0.3.2 typecheck /home/christian/js/relay
> flow check src/

find: "/home/christian/js/relay/node_modules/fbjs/node_modules/promise": No such file or directory
find: "/home/christian/js/relay/node_modules/fbjs/node_modules/promise": No such file or directory

Found 0 errors
Using Jest CLI v0.5.8
 FAIL  src/legacy/store/__tests__/GraphQLRange-test.js 
● Runtime Error
TypeError: /home/christian/js/relay/node_modules/fbjs-scripts/jest/environment.js: /home/christian/js/relay/node_modules/core-js/es6/index.js: /home/christian/js/relay/node_modules/core-js/modules/es6.symbol.js: Cannot read property 'type' of null
  at makeComponent (/home/christian/js/relay/node_modules/jest-cli/src/lib/moduleMocker.js:83:19)
  at generateMock (/home/christian/js/relay/node_modules/jest-cli/src/lib/moduleMocker.js:232:16)
  at Object.generateFromMetadata (/home/christian/js/relay/node_modules/jest-cli/src/lib/moduleMocker.js:265:14)
  at Loader._generateMock (/home/christian/js/relay/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:278:23)
  at Loader.requireMock (/home/christian/js/relay/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:795:43)
  at Loader.requireModuleOrMock (/home/christian/js/relay/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:918:17)
  at Object.<anonymous> (/home/christian/js/relay/node_modules/core-js/modules/es6.symbol.js:4:22)
  at Object.runContentWithLocalBindings (/home/christian/js/relay/node_modules/jest-cli/src/lib/utils.js:517:17)
  at Loader._execModule (/home/christian/js/relay/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:236:9)
  at Loader.requireModule (/home/christian/js/relay/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:899:12)
  at Loader._generateMock (/home/christian/js/relay/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:267:30)
  at Loader.requireMock (/home/christian/js/relay/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:795:43)
  at Loader.requireModuleOrMock (/home/christian/js/relay/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:918:17)
  at Object.<anonymous> (/home/christian/js/relay/node_modules/core-js/es6/index.js:1:98)
  at Object.runContentWithLocalBindings (/home/christian/js/relay/node_modules/jest-cli/src/lib/utils.js:517:17)
  at Loader._execModule (/home/christian/js/relay/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:236:9)
  at Loader.requireModule (/home/christian/js/relay/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:899:12)
  at Loader._generateMock (/home/christian/js/relay/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:267:30)
  at Loader.requireMock (/home/christian/js/relay/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:795:43)
  at Loader.requireModuleOrMock (/home/christian/js/relay/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:918:17)
  at Object.<anonymous> (/home/christian/js/relay/node_modules/fbjs-scripts/jest/environment.js:1:83)
  at Object.runContentWithLocalBindings (/home/christian/js/relay/node_modules/jest-cli/src/lib/utils.js:517:17)
  at /home/christian/js/relay/node_modules/jest-cli/src/TestRunner.js:362:13

**Comment by wincent** [comment]
Thanks for reporting this, @clentfort. I don't think any of us have updated to npm v3 yet (and I personally haven't because I am wary of productivity-sapping teething problems like this one), but it would be nice to deal with this before v3 is declared "final".

I've added the "help wanted" tag to see if anybody wants to jump in and help out with this before we get to it.

**Comment by zpao** [comment]
If we want to be strict and only support npm@2 we can add the devEngines check we have in React.

**Comment by clentfort** [comment]
@zapo I guess that would be a good solution for the moment.
@wincent Arch Linux already uses to npm3 by default, that's how I encountered this problem.

**Comment by wincent** [comment]
Spring cleaning, so I threw up https://github.com/facebook/relay/pull/495 for this.

@zpao: I see that you relaxed the requirement in React a few days ago, but I don't think we're ready to go there yet.

**Comment by zpao** [comment]
Yea, Relay will have issues but React escapes because we don't use Flow there. That part kinda sucks but hopefully will get fixed by the work @gabelevi is doing (can't find the issue right now).

**Comment by josephsavona** [comment]
Closing as Relay now explicitly sets its required node/npm versions in package.json

**Comment by prewk** [comment]
@clentfort This is the only place I found the `es6.symbol.js: Cannot read property 'type' of null` error when googling. I'm getting the same thing when trying to run `babel-jest` on a js module with flow types. It triggers on `function foo(bar: Object) {}` but not on `function foo(bar: any) {}`.

Can you provide any guidance? (This question has nothing to do with `relay`)

**Comment by clentfort** [comment]
@prewk: If you have a question regarding the usage of jest please turn to [StackOverflow](http://stackoverflow.com/questions/tagged/jestjs) or their [Discord-Channel](https://discordapp.com/channels/102860784329052160/103622435865104384). If you think you encountered a bug with babe-jest or jest please report it on the respective GitHub project.

**Comment by prewk** [comment]
I had a specific problem concerning a specific error message which you and I are alone on the internet to encounter it seems. That's why I asked here. I'll try elsewhere, thanks.
