### ISSUE TITLE
react.createContext is not a function at createRelayContext (Reaact server component, Nextjs 13)

### ISSUE THREAD

**Issue by Roshanjossey** [facebook/relay#4118]
I'm trying out [step by step guide ](https://relay.dev/docs/getting-started/step-by-step-guide/) in Nextjs 13 boiler plate and I'm getting this error.

Full error log

<details>
<summary>Error log</summary>

```
error - [rendering] [root of the dev server]/  Error during SSR Rendering
  TypeError: react.createContext is not a function
    at createRelayContext (.next/server/app/chunks/rsc/_307f9f.js:21:25)
    at Object.<anonymous> (.next/server/app/chunks/rsc/node_modules_65e15a.js:17:17)
    at Object.[project-with-next]/node_modules/react-relay/lib/ReactRelayContext.js (ecmascript, rsc) (.next/server/app/chunks/rsc/node_modules_65e15a.js:78:3)
    at <unknown> (.next/server/app/chunks/ssr/_65cb9a.js:3103:21)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_65cb9a.js:3141:5)
    at instantiateModule (.next/server/app/chunks/ssr/_65cb9a.js:3102:5)
    at getOrInstantiateModuleFromParent (.next/server/app/chunks/ssr/_65cb9a.js:3183:12)
    at commonJsRequire (.next/server/app/chunks/ssr/_65cb9a.js:2927:12)
    at Object.<anonymous> (.next/server/app/chunks/rsc/node_modules_65e15a.js:12:24)
    at Object.[project-with-next]/node_modules/react-relay/lib/index.js (ecmascript, rsc) (.next/server/app/chunks/rsc/node_modules_65e15a.js:70:3)
    at <unknown> (.next/server/app/chunks/ssr/_65cb9a.js:3103:21)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_65cb9a.js:3141:5)
    at instantiateModule (.next/server/app/chunks/ssr/_65cb9a.js:3102:5)
    at getOrInstantiateModuleFromParent (.next/server/app/chunks/ssr/_65cb9a.js:3183:12)
    at commonJsRequire (.next/server/app/chunks/ssr/_65cb9a.js:2927:12)
    at Object.<anonymous> (.next/server/app/chunks/rsc/node_modules_65e15a.js:10:17)
    at Object.[project-with-next]/node_modules/react-relay/index.js (ecmascript, rsc) (.next/server/app/chunks/rsc/node_modules_65e15a.js:7:3)
    at <unknown> (.next/server/app/chunks/ssr/_65cb9a.js:3103:21)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_65cb9a.js:3141:5)
    at instantiateModule (.next/server/app/chunks/ssr/_65cb9a.js:3102:5)
    at getOrInstantiateModuleFromParent (.next/server/app/chunks/ssr/_65cb9a.js:3183:12)
    at esmImport (.next/server/app/chunks/ssr/_65cb9a.js:2912:20)
    at <unknown> (.next/server/app/chunks/rsc/app_0b2646.js:1:0)
    at Module.[project-with-next]/app/page.tsx (ecmascript, rsc) (.next/server/app/chunks/rsc/app_0b2646.js:89:3)
    at <unknown> (.next/server/app/chunks/ssr/_65cb9a.js:3103:21)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_65cb9a.js:3141:5)
    at instantiateModule (.next/server/app/chunks/ssr/_65cb9a.js:3102:5)
    at getOrInstantiateModuleFromParent (.next/server/app/chunks/ssr/_65cb9a.js:3183:12)
    at esmImport (.next/server/app/chunks/ssr/_65cb9a.js:2912:20)
    at <unknown> (.next/server/app/chunks/rsc/app_0b2646.js:1:0)
    at Module.[project-with-next]/app/page.tsx/layout-entry.tsx (ecmascript, rsc) (.next/server/app/chunks/rsc/app_0b2646.js:172:3)
    at <unknown> (.next/server/app/chunks/ssr/_65cb9a.js:3103:21)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_65cb9a.js:3141:5)
    at instantiateModule (.next/server/app/chunks/ssr/_65cb9a.js:3102:5)
    at getOrInstantiateModuleFromParent (.next/server/app/chunks/ssr/_65cb9a.js:3183:12)
    at esmImport (.next/server/app/chunks/ssr/_65cb9a.js:2912:20)
    at Module.default (.next/server/app/chunks/rsc/app_bb5484.js:6:18)
    at <unknown> (.next/server/app/chunks/ssr/_65cb9a.js:12:23)
    at Module.[project-with-next]/app/entry (ecmascript, ssr) (.next/server/app/chunks/ssr/_65cb9a.js:337:3)
    at <unknown> (.next/server/app/chunks/ssr/_65cb9a.js:3103:21)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_65cb9a.js:3141:5)
    at instantiateModule (.next/server/app/chunks/ssr/_65cb9a.js:3102:5)
    at instantiateRuntimeModule (.next/server/app/chunks/ssr/_65cb9a.js:3687:12)
    at <unknown> (.next/server/app/chunks/ssr/_65cb9a.js:2742:1)
    at <unknown> (.next/server/app/chunks/ssr/_65cb9a.js:3738:39)
    at <anonymous>
    at Object.registerChunk [as push] (.next/server/app/chunks/ssr/_65cb9a.js:3738:25)
    at Object.<anonymous> (.next/server/app/chunks/rsc/node_modules_next_dist_client_components_0c686c.js:1:41)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (.next/server/app/index.js:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at <unknown> (node:internal/main/run_main_module:17:47)
  
  
  | Node.js exit code: 1
```

</details>

If you wanna try it out, you can find the code in https://github.com/Roshanjossey/nextjs-13-relay

Is this happening because usePreloadedQuery is not supposed to be used with SSR?

**Comment by tinleym** [comment]
That's happening because you can't use context in server components.

I think there is some path where you can load the data on the server, and then use it to populate the cache on the client (I'm still trying to work that out myself).

Unfortunately, the mechanisms required accomplishing this aren't documented, to my my knowledge. There is an example repo that shows how to follow this pattern pre Next 13, using getServerSideProps. Mind that it's also exhibiting an advanced undocumented feature called Data-Driven Dependencies.

https://github.com/relayjs/relay-examples/tree/main/data-driven-dependencies

**Comment by Roshanjossey** [comment]
Thank you for your reply @tinleym, would you like to collaborate on documenting this?

**Comment by tinleym** [comment]
You're welcome! What did you have in mind re: documentation? On the Next side, they cover this limitation:
https://beta.nextjs.org/docs/rendering/server-and-client-components#context

On the Relay side, re: data fetched on the server, I'm still poking around, trying to figure things out... I don't think I have it pinned down to where I should be offering guidance :)

**Comment by alunyov** [comment]
@tinleym is correct.

> That's happening because you can't use context in server components.

I don't think this is Relay issue. I'm closing this for now. But I commented on what I think the direction for Relay and Next.js integration may be: https://github.com/facebook/relay/issues/4107
