### ISSUE TITLE
storybook with react relay

### ISSUE THREAD

**Issue by EfraimDim** [facebook/relay#4149]
I am trying to use react relay mocks to mock data with storybook and django graphene relay connections, here is my mock:

```
environment.mock.queueOperationResolver((operation: any) => {
  MockPayloadGenerator.generate(operation, {
    RunNodeConnection() {
      return {
        edges: [
          {
            node: {
              uuid: "cfccaa5e-0827-4cc8-b74a-dv5cde27ade4",
              commit: "dsfdsg",
              branch: "default",
              defaultBranch: "main",
              analysed: true,
            },
          },
        ],
      };
    },
    RunNodeEdge() {
      return [
        {
          node: {
            uuid: "cfccaa5e-0827-4cc8-b74a-dv5cde27ade4",
            commit: "dsfdsg",
            branch: "default",
            defaultBranch: "main",
            analysed: true,
          },
        },
      ];
    },
    RunNode() {
      return {
        node: {
          uuid: "cfccaa5e-0827-4cc8-b74a-dv5cde27ade4",
          commit: "dsfdsg",
          branch: "default",
          defaultBranch: "main",
          analysed: true,
        },
      };
    },
  });
});

const query = graphql`
  query PullRequestRunsQuery($pull_Uuid: UUID!) {
    runs(pull_Uuid: $pull_Uuid, orderBy: "-created") {
      edges {
        node {
          uuid
          commit
          branch
          defaultBranch
          analysed
        }
      }
    }
  }

const variables = {
  pull_Uuid: "cfccaa5e-0827-4cc8-b74a-0f5cde27ade4",
};

environment.mock.queuePendingOperation(query, variables);

const preloadedQuery = loadQuery(environment, query, variables);

  return (
    <RelayEnvironmentProvider environment={environment}>
        <React.Suspense fallback={<div></div>}>
          {preloadedQuery && (
            <RunsList
              queryGetRunsOfPullReference={preloadedQuery}
              pullRequestRunsQuery={query}
              setRunUuidSelected={setRunUuidSelected}
            />
          )}
        </React.Suspense>
    </RelayEnvironmentProvider>
```

the relevant part of the result of `console.log(JSON.stringify(operation, null, 2))` is:

```{
  "fragment": {
    "kind": "SingularReaderSelector",
    "dataID": "client:root",
    "isWithinUnmatchedTypeRefinement": false,
    "node": {
      "argumentDefinitions": [
        {
          "defaultValue": null,
          "kind": "LocalArgument",
          "name": "pull_Uuid"
        }
      ],
      "kind": "Fragment",
      "metadata": null,
      "name": "PullRequestRunsQuery",
      "selections": [
        {
          "alias": null,
          "args": [
            {
              "kind": "Literal",
              "name": "orderBy",
              "value": "-created"
            },
            {
              "kind": "Variable",
              "name": "pull_Uuid",
              "variableName": "pull_Uuid"
            }
          ],
          "concreteType": "RunNodeConnection",
          "kind": "LinkedField",
          "name": "runs",
          "plural": false,
          "selections": [
            {
              "alias": null,
              "args": null,
              "concreteType": "RunNodeEdge",
              "kind": "LinkedField",
              "name": "edges",
              "plural": true,
              "selections": [
                {
                  "alias": null,
                  "args": null,
                  "concreteType": "RunNode",
                  "kind": "LinkedField",
                  "name": "node",
                  "plural": false,
                  "selections": [
                    {
                      "alias": null,
                      "args": null,
                      "kind": "ScalarField",
                      "name": "uuid",
                      "storageKey": null
                    },
                    {
                      "alias": null,
                      "args": null,
                      "kind": "ScalarField",
                      "name": "commit",
                      "storageKey": null
                    },
                    {
                      "alias": null,
                      "args": null,
                      "kind": "ScalarField",
                      "name": "branch",
                      "storageKey": null
                    },
                    {
                      "alias": null,
                      "args": null,
                      "kind": "ScalarField",
                      "name": "defaultBranch",
                      "storageKey": null
                    },
                    {
                      "alias": null,
                      "args": null,
                      "kind": "ScalarField",
                      "name": "analysed",
                      "storageKey": null
                    }
                  ],
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
```

my error message is: 

```
Uncaught TypeError: environment.getStore(...).getEpoch is not a function
    at FragmentResourceImpl.readWithIdentifier (FragmentResource.js:229:1)
    at useFragmentNode (useFragmentNode.js:39:1)
    at useLazyLoadQueryNode (useLazyLoadQueryNode.js:108:1)
    at usePreloadedQuery (usePreloadedQuery.js:106:1)
    at RunsList (RunsList.tsx:14:1)
    at renderWithHooks (react-dom.development.js:16141:1)
    at mountIndeterminateComponent (react-dom.development.js:20838:1)
    at beginWork (react-dom.development.js:22342:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4157:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4206:1)
```

any idea how to resolve? thanks so much

** the RunsList component uses usePreloadedQuery hook

**Comment by daniloab** [comment]
cc @sibelius

**Comment by EfraimDim** [comment]
@sibelius doesn't show an example with usePreloadedQuery which is what im am trying to implement

**Comment by EfraimDim** [comment]
So i've found the answer:

so for storybook you need to add these imports:

```import { RecordSource, Store } from "relay-runtime";```

and for storybook when creating the mock environment you need to create a store to:

```const environment = createMockEnvironment({
  store: new Store(new RecordSource()),
});```

finally when you export you need to add this:

```export const current = Template.bind({});
current.parameters = {
  docs: {
    source: {
      code: "Disabled for this story, see https://github.com/storybookjs/storybook/issues/11554",
    },
  },
};```

I hope this helps someone else took me months to solve haha
