### ISSUE TITLE
[relay-test-utils] createMockEnvironment expects jest to be defined

### ISSUE THREAD

**Issue by rachel-church** [facebook/relay#4228]
The `package.json` file of `relay-test-utils` does not require `jest`, but attempting to use `createMockEnvironment` in any test runner except for `jest` will result in the following error:

```
ReferenceError: jest is not defined
      at mockDisposableMethod (node_modules/relay-test-utils/lib/RelayModernMockEnvironment.js:40:17)
      at Object.createMockEnvironment (node_modules/relay-test-utils/lib/RelayModernMockEnvironment.js:354:5)
```

It looks like `RelayModernMockEnvironment` utilizes `jest.fn` under the hood to [create mock methods](https://github.com/facebook/relay/blob/v14.1.0/packages/relay-test-utils/RelayModernMockEnvironment.js#L52) on the `Environment` object.

This issue prevents users from using `createMockEnvironment` with test runners such as [vitest](https://vitest.dev/guide/why.html), `mocha`, `jasmine`, [ava](https://github.com/avajs/ava), etc. 

Reproduction using `mocha`: https://glitch.com/edit/#!/frost-tulip-polka

**Comment by rachel-church** [comment]
It looks like this could be an easy fix by adding a dependency on `jest-mock` and conditionally using it if the global jest instance isn't defined.

`packages/relay-test-utils/RelayModernMockEnvironment.js`
```js
const jest = typeof jest === 'undefined' ? new require('jest-mock').ModuleMocker(global) : jest;
```

Would `jest-mock` need to be a `peerDependency` or a `dependency`?

**Comment by sibelius** [comment]
- peerDependency

**Comment by Dmo16** [comment]
Forgive my ignorance here, just started using Relay myself with a Vite/Vitest app.

Is there a suggested workaround I can employ until this is fixed?

**Comment by jhsu** [comment]
@Dmo16 for a workaround, in a `setupFiles`, i put:

```
import {vi} from 'vitest'
global.jest = vi
`

**Comment by sibelius** [comment]
anybody got an example of using vitest with relay?

anybody willing to pursue a pull request to fix this ?
