### ISSUE TITLE
Server Exception in Tutorial Newsfeed Example 

### ISSUE THREAD

**Issue by ottoborden** [facebook/relay#4612]
New to React and GraphQL. Working through the tutorial and I'm having issues locally on the first example. Added the NewfeedQuery and updated the Story component. FWIW, my IDE is telling me data.topStory is not defined.

```
import * as React from "react";
import Story from "./Story";
import { graphql } from 'relay-runtime';
import { useLazyLoadQuery } from "react-relay";

const NewsfeedQuery = graphql`
  query NewsfeedQuery {
    topStory {
      title
      summary
      poster {
        name
        profilePicture {
          url
        }
      }
      thumbnail {
        url
      }
    }
  }
`;

export default function Newsfeed({}) {
  const data = useLazyLoadQuery(
    NewsfeedQuery,
    {},
  );
  const story = data.topStory;
  // As before:
  return (
    <div className="newsfeed">
      <Story story={story} />
    </div>
  );
}

```

Now getting this in the logs:
```
[server] request received: /api
[server] /home/user/scratch/relay-examples/newsfeed/node_modules/graphql/execution/execute.js:75
[server]     throw new Error(UNEXPECTED_EXPERIMENTAL_DIRECTIVES);
[server]           ^
[server] 
[server] Error: The provided schema unexpectedly contains experimental directives (@defer or @stream). These directives may only be utilized if experimental execution features are explicitly enabled.
[server]     at execute (/home/user/scratch/relay-examples/newsfeed/node_modules/graphql/execution/execute.js:75:11)
[server]     at graphql (file:///home/user/scratch/relay-examples/newsfeed/server/index.mjs:38:10)
[server]     at Server.<anonymous> (file:///home/user/scratch/relay-examples/newsfeed/server/index.mjs:68:22)
[server]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[server] 
[server] Node.js v20.11.0
[webpack] <e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:3000/api to http://localhost:8080/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
[server] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by ottoborden** [comment]
I had accidentally run `npm update`. Deleted and re-cloned and the issue is now resolved.
