### ISSUE TITLE
babel-relay-plugin webpack setup

### ISSUE THREAD

**Issue by Agrosis** [facebook/relay#468]
Hello, I can't seem to get the babel-relay-plugin to work with my webpack config. So far I have:

```
var webpack = require('webpack');

module.exports = {
  devtool: 'inline-source-map',

  entry: {
    app: ['webpack/hot/dev-server', './javascripts/entry.js'],
  },

  output: {
    path: './public/built',
    publicPath: '/built/',
    filename: 'bundle.js'
  },

  devServer: {
    contentBase: "public",
    publicPath: 'http://localhost:3030/built/',
    historyApiFallback: true
  },

  module: {
    loaders: [
      { test: /\.js$/, loader: 'babel', exclude: /node_modules/, query: { stage: 0, plugins: ['./plugins/babelRelayPlugin'] } },
      { test: /\.css$/, loader: 'style-loader!css-loader' },
      { test: /\.less$/, loader: 'style-loader!css-loader!less-loader' }
    ]
  },

  plugins: [
    new webpack.ProvidePlugin({
      'Promise': 'es6-promise',
      'fetch': 'imports?this=>global!exports?global.fetch!whatwg-fetch'
    })
  ]
};
```

And whenever I run `webpack-dev-server --hot --inline --port 3030 --host 0.0.0.0`, I get the following error:

```
bundle.js  661 kB       0  [emitted]  app
chunk    {0} bundle.js (app) 216 kB [rendered]
    [0] multi app 64 bytes {0} [built] [1 error]
    [1] (webpack)-dev-server/client?http://0.0.0.0:3030 2.14 kB {0} [built]
    [2] ./~/node-libs-browser/~/url/url.js 22.3 kB {0} [built]
    [3] ./~/node-libs-browser/~/punycode/punycode.js 14.6 kB {0} [built]
...
   [60] (webpack)/hot/log-apply-result.js 813 bytes {0} [built]

ERROR in ./javascripts/entry.js
Module build failed: SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at PluginManager.subnormaliseString (/Users/mahsan/Desktop/x/y/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/plugin-manager.js:141:20)
    at PluginManager.add (/Users/mahsan/Desktop/x/y/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/plugin-manager.js:190:40)
    at File.buildTransformers (/Users/mahsan/Desktop/x/y/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:237:21)
 @ multi app
```

I have a `schema.json` inside `data/`, and my `plugins/babelRelayPlugin` is:
```
import getBabelRelayPlugin from 'babel-relay-plugin';

var schema = require('../data/schema.json');

export default getBabelRelayPlugin(schema.data);
```

Here is my package.json:
```
"devDependencies": {
    "babel-core": "^5.8.21",
    "babel-loader": "^5.3.2",
    "babel-relay-plugin": "^0.3.0",
    "css-loader": "^0.15.6",
    "exports-loader": "^0.6.2",
    "imports-loader": "^0.6.4",
    "less": "^2.5.1",
    "less-loader": "^2.2.0",
    "node-libs-browser": "^0.5.2",
    "webpack": "^1.12.2",
    "webpack-dev-server": "^1.12.0"
  }
```

This has been stumping me for a bit, some help would be really nice!

EDIT: Some more info, I also do code splitting in this app, but I made sure that none of this is happening because of any code. it seems to be webpack.

**Comment by Agrosis** [comment]
Ugh, I figured it out. Appaerntly `webpack.config.js` needs to be renamed to `webpack.config.babel.js`. I have no clue why this works, would someone be able to tell me why, before I close it?

**Comment by josephsavona** [comment]
@Agrosis Thanks for following up that you were able to resolve the issue :-) Maybe consult the webpack docs about the config file naming?
