### ISSUE TITLE
Error loading react-relay's RootContainer on the server 

### ISSUE THREAD

**Issue by rattrayalex** [facebook/relay#504]
Hi, 

I don't get this error when I avoid loading the relay components on the server, and I don't get this error when I do load the relay components on the client. FWIW, I'm using `koa-graphql` and `react-router`. The base route on my react-router points to the `Relay.RootContainer`, whose `Component` is the relay Container around my base React component. 

Stack trace:

```
XMLHttpRequest is not defined
Warning: React can't find the root component node for data-reactid value `.yrhkjupxj4`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.
/Users/alex/djcode/react-relay-router-koa/node_modules/react-relay/node_modules/fbjs/lib/resolveImmediate.js:28
    throw error;
    ^

TypeError: Cannot read property 'firstChild' of undefined
    at Object.ReactMount.findComponentRoot (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactMount.js:710:39)
    at Object.ReactMount.findReactNodeByID (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactMount.js:674:23)
    at Object.getNode (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactMount.js:162:32)
    at Object.ReactDOMIDOperations.dangerouslyProcessChildrenUpdates (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactDOMIDOperations.js:83:42)
    at Object.wrapper [as processChildrenUpdates] (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactPerf.js:66:21)
    at processQueue (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactMultiChild.js:160:31)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateTextContent (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactMultiChild.js:277:13)
    at ReactDOMComponent.Mixin._updateDOMChildren (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactDOMComponent.js:857:12)
    at ReactDOMComponent.Mixin.updateComponent (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactDOMComponent.js:701:10)
    at ReactDOMComponent.Mixin.receiveComponent (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactDOMComponent.js:646:10)
    at Object.ReactReconciler.receiveComponent (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactReconciler.js:87:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactCompositeComponent.js:562:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactCompositeComponent.js:473:12)
    at [object Object].wrapper [as updateComponent] (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactPerf.js:66:21)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactCompositeComponent.js:405:10)
    at Object.ReactReconciler.receiveComponent (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactReconciler.js:87:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactCompositeComponent.js:562:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactCompositeComponent.js:473:12)
    at [object Object].wrapper [as updateComponent] (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactPerf.js:66:21)
    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/alex/djcode/react-relay-router-koa/node_modules/react/lib/ReactCompositeComponent.js:421:12)
```

**Comment by steveluscher** [comment]
Server rendering support is in the works. Follow along in #136!
