### ISSUE TITLE
Install error in babel-relay-plugin

### ISSUE THREAD

**Issue by andresallvs** [facebook/relay#723]
Please check the attached log.

Thanks.
[npm-debug.log.txt](https://github.com/facebook/relay/files/78872/npm-debug.log.txt)

**Comment by andresalves** [comment]
This solve the problem. https://github.com/relayjs/relay-starter-kit/issues/56

In short, update the old version of global babel-core and babel-cli.

npm install -g babel-core

npm install -g babel-cli

**Comment by andresalves** [comment]
Sorry, that link don't solve the problem. 

I think the problem are incompatibilty of react-relay@0.6.0 and babel-relay-plugin@0.6.2 versions. For apps in examples folder.

Maybe incompatibility with Node@5.3.0 and NPM@3.5.2. 

To see the apps in examples folder, i add react-relay@0.6.0 and babel-relay-plugin@0.6.0 in each package.js files and install. That works.

**Comment by BerndWessels** [comment]
@andresalves There is no babel-relay-plugin@0.6.2 as far as I can see, only a babel-relay-plugin@0.6.1 - and that is actually kind of the same like 0.6.0 but react-relay wants exactly 0.6.0.
react-relay and babel-relay-plugin are supposed to be in sync and they will be again as soon as 0.7.0 is released.

**Comment by andresalves** [comment]
Ok @BerndWessels, but in npm-debug.log.txt you can see:

184 silly resolveWithNewModule babel-relay-plugin@0.6.2 checking installable status

Thanks!

**Comment by kaizhu256** [comment]
can you lockdown the npm package versions? npm install fails for /examples/todo.

```
kaizhu@minime2:~/src/relay/examples/todo$ npm install

> babel-relay-plugin@0.6.3 prepublish /Users/kaizhu/src/relay/scripts/babel-relay-plugin
> npm run build


> babel-relay-plugin@0.6.3 build /Users/kaizhu/src/relay/scripts/babel-relay-plugin
> scripts/build-lib

/Users/kaizhu/node_modules/babel/index.js:1
(function (exports, require, module, __filename, __dirname) { throw new Error("The node API for `babel` has been moved to `babel-core`.");
                                                              ^

Error: The node API for `babel` has been moved to `babel-core`.
    at Object.<anonymous> (/Users/kaizhu/node_modules/babel/index.js:1:69)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kaizhu/src/relay/scripts/babel-relay-plugin/scripts/build-lib:3:13)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! babel-relay-plugin@0.6.3 build: `scripts/build-lib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the babel-relay-plugin@0.6.3 build script 'scripts/build-lib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the babel-relay-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/build-lib
npm ERR! You can get their info via:
npm ERR!     npm owner ls babel-relay-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kaizhu/src/relay/scripts/babel-relay-plugin/npm-debug.log
npm ERR! addLocal Could not install /Users/kaizhu/src/relay/scripts/babel-relay-plugin

> react-relay@0.6.1 prepublish /Users/kaizhu/src/relay
> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json && npm run build

module.js:328
    throw err;
    ^

Error: Cannot find module '/Users/kaizhu/src/relay/node_modules/fbjs-scripts/node/check-dev-engines.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
npm ERR! addLocal Could not install /Users/kaizhu/src/relay
npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! babel-relay-plugin@0.6.3 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the babel-relay-plugin@0.6.3 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the babel-relay-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls babel-relay-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kaizhu/src/relay/examples/todo/npm-debug.log```

**Comment by naomik** [comment]
I have a freshly-installed node `5.6.0`

`npm install` fails

```txt
~/code/facebook/relay/examples/todo
 % npm install

> babel-relay-plugin@0.7.0 prepublish /Users/naomik/code/facebook/relay/scripts/babel-relay-plugin
> npm run build


> babel-relay-plugin@0.7.0 build /Users/naomik/code/facebook/relay/scripts/babel-relay-plugin
> scripts/build-lib

module.js:341
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/naomik/code/facebook/relay/scripts/babel-relay-plugin/scripts/build-lib:6:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/versions/node/5.6.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! babel-relay-plugin@0.7.0 build: `scripts/build-lib`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the babel-relay-plugin@0.7.0 build script 'scripts/build-lib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the babel-relay-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/build-lib
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs babel-relay-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls babel-relay-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/naomik/code/facebook/relay/scripts/babel-relay-plugin/npm-debug.log
npm ERR! addLocal Could not install /Users/naomik/code/facebook/relay/scripts/babel-relay-plugin

> react-relay@0.7.0 prepublish /Users/naomik/code/facebook/relay
> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json && npm run build

module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/naomik/code/facebook/relay/node_modules/fbjs-scripts/node/check-dev-engines.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3

npm ERR! addLocal Could not install /Users/naomik/code/facebook/relay
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/versions/node/5.6.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! babel-relay-plugin@0.7.0 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the babel-relay-plugin@0.7.0 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the babel-relay-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs babel-relay-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls babel-relay-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/naomik/code/facebook/relay/examples/todo/npm-debug.log
```

**Comment by kassens** [comment]
You're correct, we're still missing support for node 5/npm 3. #832 tracks to get us updated.
