### ISSUE TITLE
Tests don't work on Windows?

### ISSUE THREAD

**Issue by ryancole** [facebook/relay#796]
I'm trying to run the Relay tests, on Windows. I have to use jest directly, because the npm script uses bash script. I'm running the tests as follows ...

```
C:\Users\Ryan\Projects\relay>set NODE_ENV=test
C:\Users\Ryan\Projects\relay>echo '%NODE_ENV%'
'test'
C:\Users\Ryan\Projects\relay>node_modules\.bin\jest
```

All tests fails due to failed imports, such as ...

```
 FAIL  src\traversal\__tests__\containsRelayQueryRootCall-test.js
● Runtime Error
Error: Cannot find module './configureForRelayOSS' from 'C:\Users\Ryan\Projects\relay\src\traversal\__tests__\containsRelayQueryRootCall-test.js'
    at Loader._nodeModuleNameToPath (C:\Users\Ryan\Projects\relay\node_modules\jest-cli\src\HasteModuleLoader\HasteModuleLoader.js:404:22)
    at Loader._moduleNameToPath (C:\Users\Ryan\Projects\relay\node_modules\jest-cli\src\HasteModuleLoader\HasteModuleLoader.js:376:19)
    at Loader._getNormalizedModuleID (C:\Users\Ryan\Projects\relay\node_modules\jest-cli\src\HasteModuleLoader\HasteModuleLoader.js:329:35)
    at Loader._shouldMock (C:\Users\Ryan\Projects\relay\node_modules\jest-cli\src\HasteModuleLoader\HasteModuleLoader.js:449:27)
    at Loader.requireModuleOrMock (C:\Users\Ryan\Projects\relay\node_modules\jest-cli\src\HasteModuleLoader\HasteModuleLoader.js:787:14)
    at Object.eval (C:\Users\Ryan\Projects\relay\src\traversal\__tests__\containsRelayQueryRootCall-test.js:14:1)
    at Loader._execModule (C:\Users\Ryan\Projects\relay\node_modules\jest-cli\src\HasteModuleLoader\HasteModuleLoader.js:206:17)
    at Loader.requireModule (C:\Users\Ryan\Projects\relay\node_modules\jest-cli\src\HasteModuleLoader\HasteModuleLoader.js:760:14)
    at jasmine2 (C:\Users\Ryan\Projects\relay\node_modules\jest-cli\src\testRunners\jasmine\jasmine2.js:103:16)
    at C:\Users\Ryan\Projects\relay\node_modules\jest-cli\src\TestRunner.js:261:14
```

Any ideas? Flow doesn't seem to work either, for what it's worth, but that's for a different issue!

**Comment by ryancole** [comment]
I should mention that I'm using node 4.x and npm 2.x, as required by package.json, as well.

**Comment by ryancole** [comment]
Strange. I tried on a different PC today - exact same OS, specs, etc - and the tests work. They still don't work on the other PC, though. No clue. *shrug*

**Comment by josephsavona** [comment]
Thanks for following up on this!
