### ISSUE TITLE
Error: TypeError: Object  has no method 'find'

### ISSUE THREAD

**Issue by varunarora** [facebook/relay#968]
I have been constantly getting the error `Error: TypeError: Object  has no method 'find'` and can't seem to understand this `Relay Transform Error` for days now. Tried all combinations. My GraphQL is setup and working (tested on Graphiql), but this is really confusing me.

```
Error: TypeError: Object  has no method 'find'
    at new RelayQLFragment (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-relay-plugin/lib/RelayQLAST.js:143:49)
    at RelayQLTransformer.processDocumentText (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-relay-plugin/lib/RelayQLTransformer.js:156:16)
    at RelayQLTransformer.transform (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-relay-plugin/lib/RelayQLTransformer.js:67:29)
    at PluginPass.TaggedTemplateExpression (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-relay-plugin/lib/getBabelRelayPlugin.js:124:36)
    at newFn (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:293:19)
    at NodePath._call (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:75:18)
    at NodePath.call (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:156:16)
    at TraversalContext.visitSingle (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:200:19)
    at Function.traverse.node (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:141:17)
    at NodePath.visit (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:115:22)
    at TraversalContext.visitQueue (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:156:16)
    at TraversalContext.visitMultiple (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:17)
    at TraversalContext.visit (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:198:19)
    at Function.traverse.node (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:141:17)
    at NodePath.visit (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:115:22)
    at TraversalContext.visitQueue (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:156:16)
    at TraversalContext.visitSingle (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:200:19)
    at Function.traverse.node (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:141:17)
    at NodePath.visit (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:115:22)
    at TraversalContext.visitQueue (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:156:16)
    at TraversalContext.visitSingle (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:200:19)
    at Function.traverse.node (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:141:17)
    at NodePath.visit (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:115:22)
    at TraversalContext.visitQueue (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:156:16)
    at TraversalContext.visitMultiple (/home/varun/Code/opencurriculum/oc_platform/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:17)

```

**Comment by varunarora** [comment]
On the slightest amount of digging in, this seems to be because the line 143 in RelayQLast tries to call `find` on an Array, which seems to be an ES2015 thing (or what I figured from the MDN page for `.find`). The rest of the modules seem to clearly be for ES5. Is that right?

**Comment by kassens** [comment]
Could it be that you're running a pretty old version of Node?

**Comment by varunarora** [comment]
NPM version is 1.3.10, and node version is v0.10.25

**Comment by edvinerikson** [comment]
Relay relies on ES6 features so you would need to polyfill these in 0.x versions of Node. 
Babel got a good polyfill: https://babeljs.io/docs/usage/polyfill/

**Comment by josephsavona** [comment]
This is a bug - the plugin is intended to work in older environments without a polyfill. We should be using the `find` helper (required at the top of the file) instead of calling `arr.find`. 

cc @kassens
